#!/usr/bin/zsh
if [ -z $1 ]; then
    echo "Requires hostname as argument"
else
    /usr/bin/hostname $1
    # Get the hostname to set as the host principal
    /usr/bin/hostname > /etc/hostname

    DEV=$(ip route | grep ^default | sed 's/^.* dev //;s/ .*$//'|head -1)
    if [ -n "$DEV" ]
    then
         IP_AND_PREFIX_LEN=$(ip -f inet addr show dev $DEV | grep 'inet '| head -1 | sed 's/^ *inet *//;s/ .*$//')
         IP=$(echo ${IP_AND_PREFIX_LEN} | cut -f1 -d'/')
         MASK=$(ipcalc -m ${IP_AND_PREFIX_LEN} | sed 's/^.*=//')
         GW=$(ip route | grep default | head -1 | sed 's/^.*via //;s/ .*$//')
         IP6_PREFIX=$(ip -f inet6 addr show dev $DEV | grep 'inet6 '| head -1 | sed 's/^ *inet6 *//;s/ .*$//')
         IP6=$(echo ${IP6_PREFIX} | cut -f1 -d'/')
         MASK6=$(echo ${IP6_PREFIX} | cut -f2 -d'/')
         GW6=$(ip -6 route | grep default | head -1 | sed 's/^.*via //;s/ .*$//')
         MAC=$(ip link show dev ${DEV} | grep 'link/ether '| head -1 | sed 's/^ *link\/ether *//;s/ .*$//')

    cat > /etc/sysconfig/network-scripts/ifcfg-${DEV} << DEVEOS
# Generated by magic
DEVICE=${DEV}
ONBOOT=yes
NETBOOT=no
BOOTPROTO=static
TYPE=Ethernet
NAME=${DEV}
DEFROUTE=yes
IPV4_FAILURE_FATAL=yes
IPV6_FAILURE_FATAL=yes
IPV6INIT=yes
PEERDNS=no
PEERROUTES=no
IPV6_AUTOCONF=no
HWADDR=${MAC}
IPADDR=${IP}
GATEWAY=${GW}
NETMASK=${MASK}
IPV6ADDR=${IP6}
#PREFIX=${MASK6}
IPV6_DEFAULTGW=${GW6}
DNS1=2001:44b8:16a:16:5054:ff:fe89:97e2
#NM_CONTROLLED=no

    DEVEOS
    fi

    # Run the client install script
    /usr/bin/nisdomainname {{ ipa_domain }}
    #  We may not need to do the per-machine install in this setup ...
    /usr/sbin/ipa-client-install --force-join --domain={{ ipa_domain }} --enable-dns-updates --mkhomedir --force-ntpd --no-dns-sshfp
    sed -i /etc/sssd/sssd.conf -e "s/services.*/services = nss\, pam\, ssh\, sudo/"
    sed -i /etc/sssd/sssd.conf -e "s/ipa_dyndns_update/dyndns_update/"
    sed -i /etc/sssd/sssd.conf -e "/dyndns_update.*/ i\\dyndns_iface = \${DEV}"
    echo "sudoers: files sss" >> /etc/nsswitch.conf
    systemctl restart sssd
    echo "YOU MUST NOW RUN THE ANSIBLE COMMON ROLE ON THIS SYSTEM"

fi
