- name: Create backup home drive
  become: yes
  file: path=/home/backup state=directory owner=backup mode=0750

- name: Ensure excludes
  become: yes
  template: src=include-list dest=/home/backup/include-list owner=backup mode=0640

- name: Deploy rdiff-scripts
  become: yes
  template: src={{ item }} dest=/home/backup/{{ item }} owner=backup mode=0750
  with_items:
    - backup.sh
    - status.sh
    - clean.sh

- name: Configure backup cron
  become: true
  template: src=1backupcron dest=/etc/cron.d/1backupcron owner=root group=root mode=0644

