
- name: Install amanda software
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
   - amanda-client
   - amanda-server

- name: Configure amanda firewall
  sudo: yes
  firewalld: service=amanda-client zone=internal permanent=yes state=enabled immediate=yes

- name: Configure amanda service socket
  sudo: yes
  service: name=amanda.socket enabled=yes state=started

- name: Configure Amanda allowed hosts
  sudo: yes
  template: src=amandahosts dest=/var/lib/amanda/.amandahosts owner=amandabackup group=disk mode=0600

- name: Create amanda mountpoints
  sudo: yes
  action: file path=/var/lib/amanda/{{ item }} owner=amandabackup group=disk mode=0750 state=directory
  with_items:
    - DailySet1
    - holding/DailySet1

- name: Create config directories
  sudo: yes
  action: file path=/etc/amanda/{{ item }} owner=amandabackup group=disk mode=0750 state=directory
  with_items:
    - DailySet1

- name: Configure amanda
  sudo: yes
  template: src={{ item }} dest=/etc/amanda/{{ item }} owner=root group=root mode=0644
  with_items:
    - DailySet1/disklist
    - DailySet1/amanda.conf
    - DailySet1/amanda-client.conf

- name: Create amanda directories
  sudo: yes
  action: file path=/var/lib/amanda/{{ item }} owner=amandabackup group=disk mode=0750 state=directory
  with_items:
    - DailySet1/vtapes

- name: Create vtape directories DailySet1
  sudo: yes
  action: file path=/var/lib/amanda/sets/DailySet1/vtapes/{{ item }} owner=amandabackup group=disk mode=0750 state=directory
  with_sequence: start=1 end=60 format=slot%d

- name: Configure amanda cron
  become: true
  template: src=1amandacron dest=/etc/cron.d/1amandacron owner=root group=root mode=0644


