- name: ensure auditd running
  sudo: yes
  service: name=auditd state=started enabled=yes

- name: deploy audit configurations
  sudo: yes
  template: src=etc/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0640
  with_items:
    - audit/auditd.conf
    - audit/rules.d/audit.rules
  notify:
    - restart auditd

