
- name: Install default software
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
   - ipa-client

- name: Configure IPA configurations
  sudo: yes
  template: src=etc/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - sysconfig/network
    - openldap/ldap.conf
    - nsswitch.conf
    - pam.d/password-auth-ac
    - pam.d/system-auth-ac
    - resolv.conf

- name: Configure secure IPA configurations
  sudo: yes
  template: src=etc/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0600
  with_items:
    - sssd/sssd.conf

- name: Ensure certmonger running
  sudo: yes
  service: name=certmonger enabled=yes state=started


### TODO: Add nsswitch, sssd and others.
# krb5.conf? ipa ca.crt? etc.?

