- name: Install default software
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
   - freeipa-client
   - openldap-clients
  when: ansible_distribution == 'Fedora'

- name: Install default software
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
   - ipa-client
   - openldap-clients
  when: ansible_distribution == 'CentOS'

- name: Configure hostname
  sudo: yes
  shell: hostname {{ inventory_hostname }}

- name: Configure domain names
  sudo: yes
  shell: /usr/bin/nisdomainname {{ ipa_domain }}


- name: Test domain join
  sudo: yes
  action: stat path="/var/lib/ipa-client/sysrestore/sysrestore.state"
  register: state

- name: Debug would join
  sudo: yes
  debug: msg='{{ state }}'
  when: state.stat.exists == false

- name: Join domain
  sudo: yes
  shell: /usr/sbin/ipa-client-install -U --force-join --domain {{ ipa_domain }} --enable-dns-updates --mkhomedir --force-ntpd --no-dns-sshfp -p '{{ ipa_domainadmin_username }}' -w '{{ ipa_domainadmin_password }}' --hostname {{ inventory_hostname }}
  when: state.stat.exists == false

# Need to add chrony to this

- name: Configure IPA configurations
  sudo: yes
  template: src=etc/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - sysconfig/network
    - openldap/ldap.conf
    - nsswitch.conf
    - pam.d/password-auth-ac
    - pam.d/system-auth-ac
    - hostname
    - hosts

- name: Configure secure IPA configurations
  sudo: yes
  template: src=etc/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0600
  with_items:
    - sssd/sssd.conf
  notify:
    - restart sssd

- name: Ensure services running
  sudo: yes
  service: name={{ item }} enabled=yes state=started
  with_items:
    - certmonger
    - sssd


### TODO: Add nsswitch, sssd and others.
# krb5.conf? ipa ca.crt? etc.?

