
- include: repos.yml
- include: firewalld.yml
  when: "'vdsm_servers' not in group_names"
- include: ipa.yml

- include: amanda.yml
  when: "'amanda_servers' not in group_names"

- include: virtual.yml
  when: "'longst_virtual_servers' in group_names"

- include: sysctl.yml

- meta: flush_handlers


