

- name: Install default software
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
    - abrt-cli
    - audit
    - gdisk
    - git
    - iotop
    - nmap
    - mlocate
    - screen
    - strace
    - vim
    - yum-utils
    - zsh
