
- name: Install httpd and ssl modules
  sudo: yes
  action: yum name={{ item }} state=present
  with_items:
    - httpd
    - mod_ssl
    - certbot

# You can get the cert with:
# certbot certonly --staging -n  --agree-tos --webroot -m william@blackhats.net.au -w /var/www/william/ -d fy.blackhats.net.au
# Or domain validation
# 

- name: Ensure content directories
  sudo: yes
  action: file path=/var/www/{{ item }} owner={{ item }} group=apache mode=u=rwX,g=rX,o=rX recurse=yes
  with_items:
    - william

- name: Deploy blog configurations
  sudo: yes
  action: template src={{ item }} dest=/etc/httpd/{{ item }} owner=root group=root mode=0644
  notify: restart httpd
  with_items:
    - conf.d/static-vhosts.conf
    - conf.d/ssl.conf

- name: Enable httpd
  sudo: yes
  action: service name=httpd state=started enabled=yes

- name: Configure Blog firewalld
  sudo: yes
  firewalld: zone=internal permanent=true state=enabled service={{ item }} immediate=true
  with_items:
    - http
    - https

- name: cron the lets encrypt renewal
  sudo: yes
  action: cron name="Renew le cert blog" minute="43" hour="8" job="/usr/bin/certbot renew" user="root"

