
- name: rebuild grub2
  become: yes
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: run network.sh
  become: yes
  shell: /root/network.sh

- name: run network-suse.sh
  become: yes
  shell: /root/network-suse.sh

- name: daemon-reload
  become: true
  command: systemctl daemon-reload

- name: restart sshd
  become: true
  action: service name=sshd state=restarted

- name: postmap
  become: true
  shell: postmap /etc/postfix/{{ item }}
  with_items:
    - transport
    - recipientmap
    - relay_recipients

- name: restart postfix
  become: true
  service: name={{ item }} state=restarted
  with_items:
    - postgrey
    - postfix

