
- name: Remove the existing VM scratch template
  local_action: ovirt
    state=absent
    instance_name={{ inventory_hostname }}
    user={{ ovirt_admin_username }}
    password={{ ovirt_admin_password }}
    url=https://mion.ipa.blackhats.net.au
    region={{ ovirt_dc }}
    zone={{ ovirt_cluster }}

- name: create pxeboot path
  sudo: yes
  action: file state=directory path=/var/www/html/pub/centos/{{ centos_version }}/{{ pxepath }}
  delegate_to: "{{ item }}"
  with_items: groups.deployment_servers

- name: sync pxeboot
  sudo: yes
  action: shell rsync -a rsync://{{ centos_mirror }}/centos/{{ centos_version }}/{{ pxepath }}/ /var/www/html/pub/centos/{{ centos_version }}/{{ pxepath }}/
  delegate_to: "{{ item }}"
  with_items: groups.deployment_servers

- name: create liveos path
  sudo: yes
  action: file state=directory path=/var/www/html/pub/centos/{{ centos_version }}/{{ liveospath }}
  delegate_to: "{{ item }}"
  with_items: groups.deployment_servers

- name: sync liveos
  sudo: yes
  action: shell rsync -a rsync://{{ centos_mirror }}/centos/{{ centos_version }}/{{ liveospath }}/ /var/www/html/pub/centos/{{ centos_version }}/{{ liveospath }}/
  delegate_to: "{{ item }}"
  with_items: groups.deployment_servers

- name: sync treeinfo
  sudo: yes
  action: shell rsync -a rsync://{{ centos_mirror }}/centos/{{ centos_version }}/os/x86_64/.treeinfo /var/www/html/pub/centos/{{ centos_version }}/os/x86_64/.treeinfo
  delegate_to: "{{ item }}"
  with_items: groups.deployment_servers

#- name: fake repo path
#  sudo: yes
#  action: file state=directory path=/var/www/html/pub/centos/{{ centos_version }}/os/x86_64/
#  delegate_to: "{{ item }}"
#  with_items: groups.deployment_servers
#
#- name: fake repo setup
#  sudo: yes
#  action: shell chdir=/var/www/html/pub/centos/{{ centos_version }}/os/x86_64/ createrepo -o ./ Packages
#  delegate_to: "{{ item }}"
#  with_items: groups.deployment_servers

- name: create ks path
  sudo: yes
  action: file state=directory path=/var/www/html/ks/{{ inventory_hostname }}/
  delegate_to: "{{ item }}"
  with_items: groups.deployment_servers

# Is there a way to make sure that the template exists? 

- name: Ensure VM exists
  local_action: ovirt
    state=present
    instance_name={{ inventory_hostname }}
    user={{ ovirt_admin_username }}
    password={{ ovirt_admin_password }}
    url=https://mion.ipa.blackhats.net.au
    resource_type=template
    instance_type=server
    image=blank_pxe
    region={{ ovirt_dc }}
    zone={{ ovirt_cluster }}
    sdomain={{ ovirt_sdomain }}

- name: config template kickstart
  sudo: yes
  action: template src=ks.conf dest=/var/www/html/ks/{{ inventory_hostname }}/ks.conf
  delegate_to: "{{ item }}"
  with_items: groups.deployment_servers

# Later we need a way to get the macaddr of the ovirt host.
# This way we can do per host config

- name: config tftp menu
  sudo: yes
  action: template src=default dest=/var/lib/tftpboot/pxelinux.cfg/default
  delegate_to: "{{ item }}"
  with_items: groups.deployment_servers


# This will PXE boot, build and STOP the instance
- name: ovirt launch instance
  local_action: ovirt
    state=started
    instance_name={{ inventory_hostname }}
    user={{ ovirt_admin_username }}
    password={{ ovirt_admin_password }}
    url=https://mion.ipa.blackhats.net.au

# Some how wait til it's done then remove the ks?


