---
- hosts: local all
  gather_facts: True
  roles:
    - bh-atomic
  vars_files:
    - ~/secure/ansible_home_secrets.yml
  vars:
    fileserver_nrpe_disks:
      - comp/backups
      - comp/home
      - comp/kanidm
      - comp/micd
      - comp/nextcloud
      - comp/pub
      - comp/zm_data
      - libvirt/img
      - libvirt/iso
      - nextcloud_db
      - unifi_data
      - zm_db



