
- name: Install openshift repo
  become: true
  action: yum state=present name=centos-release-openshift-origin

- name: install openshift dependencies
  become: true
  action: yum state=present name={{ item }} enablerepo=centos-openshift-origin-testing
  with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - bridge-utils
    - bash-completion
    - gcc
    - python-virtualenv
    - docker
    - origin-clients
    - atomic-openshift-utils
    - ansible
    - pyOpenSSL
    - docker
    - docker-selinux

- name: clone ansible repo
  become: true
  action: git repo=https://github.com/openshift/openshift-ansible dest=/root/openshift-ansible
  when: "'openshift_master_servers' in group_names"

# Configure the insecure registry here.

- name: sysctl disable ipv6 because openshift is fucking retarded and forgot that the world moved on.
  template: src=90-disable-ipv6.conf dest=/etc/sysctl.d/90-disable-ipv6.conf owner=root group=root mode=0644
  become: true

- name: docker sysconfig
  become: true
  action: template src=docker dest=/etc/sysconfig/docker owner=root group=root mode=0644

- name: enable docker
  become: true
  action: service name=docker enabled=yes state=started

- name: deploy cluster information
  become: true
  action: template src=hosts dest=/etc/ansible/hosts owner=root group=root mode=0644

- name: deploy weakened sshd_config
  become: true
  action: template src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0644

- name: deploy notes
  become: true
  action: template src=notes dest=/root/notes owner=root group=root mode=0644

- name: Resize /var for master
  become: true
  lvol: vg=vg00 lv=var_lv size=20g
  notify:
    - resize xfs
    - remount xfs
  when: "'openshift_master_servers' in group_names"

- name: Resize /var for node
  become: true
  lvol: vg=vg00 lv=var_lv size=15g
  notify:
    - resize xfs
    - remount xfs
  when: "'openshift_node_servers' in group_names"

# See https://docs.openshift.org/latest/install_config/persistent_storage/persistent_storage_nfs.html

- name: allow containers to nfs
  become: true
  action: seboolean name=virt_use_nfs state=yes persistent=yes

- name: allow containers to nfs sandbox
  become: true
  action: seboolean name=virt_sandbox_use_nfs state=yes persistent=yes

