
- name: Install mail software
  become: true
  yum:
    name: ['postfix', 'postgrey', 'httpd', 'certbot', 'python2-certbot-apache']
    state: present

- name: Deploy postfix hash configurations
  become: true
  template: src=etc/postfix/{{ item }} dest=/etc/postfix/{{ item }} owner=root group=root mode=0644
  with_items:
    - transport
    - relay_recipients
    - recipientmap
  notify:
    - postmap
    - restart postfix

- name: Deploy postfix configurations
  become: true
  template: src=etc/postfix/{{ item }} dest=/etc/postfix/{{ item }} owner=root group=root mode=0644
  with_items:
    - main.cf
    - postgrey_whitelist_clients.local
  notify: restart postfix

## When some things like transport are deployed, rehash them

- name: Enable mail services
  become: true
  service: name={{ item }} state=started enabled=yes
  with_items:
    - postfix
    - postgrey
    - httpd
    - certbot-renew.timer

# Comment out /etc/httpd/conf.d/welcome.conf

# On cassia:
#    certbot certonly --apache -d mx02.blackhats.net.au -m william@blackhats.net.au --agree-tos

# On adara:
#    certbot certonly --apache -d mx03.blackhats.net.au -m william@blackhats.net.au --agree-tos


- name: config email firewalld
  become: true
  firewalld: service=smtp zone=internal permanent=yes state=enabled immediate=yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: config email ports firewalld
  become: true
  firewalld: port=465/tcp zone=internal permanent=yes state=enabled immediate=yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"


