
- name: Install mail software
  sudo: yes
  action: yum name={{ item }} state=present
  with_items:
    - postfix
    - postgrey

- name: Deploy postfix hash configurations
  sudo: yes
  template: src=etc/postfix/{{ item }} dest=/etc/postfix/{{ item }} owner=root group=root mode=0644
  with_items:
    - transport
    - relay_recipients
    - recipientmap
  notify:
    - postmap
    - restart postfix

- name: Deploy postfix configurations
  sudo: yes
  template: src=etc/postfix/{{ item }} dest=/etc/postfix/{{ item }} owner=root group=root mode=0644
  with_items:
    - main.cf
    - postgrey_whitelist_clients.local
  notify: restart postfix

- name: Check postfix keys
  sudo: yes
  register: crtst
  action: stat path="/etc/pki/tls/private/mail.firstyear.id.au.key"

# Clean up if they don't exist

#- name: Deploy postfix certificates
#  sudo: yes
#  action: command ipa-getcert request -k /etc/pki/tls/private/mail.firstyear.id.au.key -f /etc/pki/tls/certs/mail.firstyear.id.au.crt -g 4096
#  when: crtst.stat.exists == false

## When some things like transport are deployed, rehash them

- name: Enable mail services
  sudo: yes
  service: name={{ item }} state=started enabled=yes
  with_items:
    - postfix
    - postgrey

- name: config email firewalld
  sudo: yes
  firewalld: service=smtp zone=internal permanent=yes state=enabled immediate=yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: config email ports firewalld
  sudo: yes
  firewalld: port=465/tcp zone=internal permanent=yes state=enabled immediate=yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"


