
- name: Install default software
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
    - amanda-client

- name: Configure amanda service socket
  sudo: yes
  service: name=amanda.socket enabled=yes state=started
  tags:
    - amanda

- name: Configure Amanda allowed hosts
  sudo: yes
  template: src=var/lib/amandahosts dest=/var/lib/amanda/.amandahosts owner=amandabackup group=disk mode=0600
  tags:
    - amanda

- name: Configure Amanda public key
  sudo: yes
  template: src=var/lib/amanda/backup-pubkey.pem dest=/var/lib/amanda/backup-pubkey.pem owner=amandabackup group=disk mode=0600
  tags:
    - amanda

# This should touch the file instead?
- name: Ensure excludes
  sudo: yes
  template: src=var/lib/amanda/exclude dest=/var/lib/amanda/exclude owner=root group=root mode=0644
  tags:
    - amanda

# Don't open amanda up to all
- name: Configure amanda firewall
  sudo: yes
  firewalld: service=amanda-client zone=internal permanent=yes state=disabled immediate=yes

- name: Configure amanda specific firewall
  sudo: yes
  firewalld: zone=internal permanent=yes state=enabled immediate=yes rich_rule='rule family="ipv6" source address="{{ item }}" service name="amanda-client" accept'
  # Is there a way to generate these ips out of the amanda hosts?
  with_items:
    - 2001:44b8:16a:11:5054:ff:feba:574/128
