- name: Update timezone
  sudo: yes
  action: command ln -sf ../usr/share/zoneinfo/Australia/Brisbane localtime

# Add new aliases ...


# Only apply this to static CentOS hosts
- include: repos.yml
  when: "ansible_form_factor != 'Notebook' and ansible_distribution == 'CentOS'"

# These are safe, useful, default packages for all installs
- include: packages.yml
# You have to be kidding that I wouldn't run anything other
#  than enforcing on my systems.
#- include: selinux.yml
#  when: ansible_selinux.status != 'disabled'

# Apply to our linodes
- include: linode.yml
  when: "'linode_servers' in group_names"

# Laptop defaults
- include: laptop.yml
  when: ansible_form_factor == "Notebook"

# Server defaults
- include: sysctl.yml
  when: ansible_form_factor != "Notebook" and ansible_distribution_major_version >= '7'

# This will capture the laptops too
- include: firewalld.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"

# How do I exclude ammy here?
- include: ipa.yml
  when: "'freeipa_servers' not in group_names"
  #when: "'linode_servers' not in group_names and 'freeipa_servers' not in group_names and ansible_hostname != 'ammy'"

# Potentially capture coredumps if things go bad.
- include: kdump.yml
  when: "'linode_servers' not in group_names"

# Enable the backup client on hosts that we can backup.
- include: amanda.yml
  when: "'amanda_servers' not in group_names and ansible_hostname != 'ammy' "

# Install guest utils on relevant hosts.
- include: libvirt-guest.yml
  when: ansible_virtualization_role == "guest"

- include: monitoring.yml

# Commit everything before we continue.
- meta: flush_handlers

# Do this last as we may lock ourselves out.
- include: security.yml


