
- name: Update timezone
  sudo: yes
  action: file state=link src=/usr/share/zoneinfo/Australia/Brisbane dest=/etc/localtime

# Add new aliases ...


# Only apply this to static CentOS hosts
- include: repos.yml
  when: "ansible_form_factor != 'Notebook' and ansible_distribution == 'CentOS'"

# These are safe, useful, default packages for all installs
- include: packages.yml

# Laptop defaults
- include: laptop.yml
  when: ansible_form_factor == "Notebook"

# Server defaults
- include: sysctl.yml
  when: ansible_form_factor != "Notebook" and ansible_distribution_major_version >= '7'

# This will capture the laptops too
- include: firewalld.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"

# How do I exclude ammy here?
- include: ipa.yml
  when: "'freeipa_servers' not in group_names"

# Potentially capture coredumps if things go bad.
- include: kdump.yml
  when: "'linode_servers' not in group_names"

# Enable the backup client on hosts that we can backup.
- include: amanda.yml
  when: "'amanda_servers' not in group_names"


- name: Deploy grub serial console changes
  sudo: yes
  action: template src=libvirt/etc/default/grub dest=/etc/default/grub owner=root group=root mode=644
  notify:
    - rebuild grub2
  when: "ansible_virtualization_role == 'guest' and 'linode_servers' not in group_names"

- include: monitoring.yml

# Commit everything before we continue.
- meta: flush_handlers

# Do this last as we may lock ourselves out.
- include: security.yml


