
custom_script: |
    runcmd:
     - 'sleep 30'
     - 'echo BEGIN'
     - 'hostname {{ inventory_hostname }}'
     - 'hostname > /etc/hostname'
     - '/usr/bin/nisdomainname {{ ipa_domain }}'
     - 'echo NISDOMAIN={{ ipa_domain }} > /etc/sysconfig/network'
     - '/usr/sbin/ipa-client-install -U --force-join --domain {{ ipa_domain }} --enable-dns-updates --mkhomedir --force-ntpd --no-dns-sshfp -p ''{{ ipa_domainadmin_username }}'' -w ''{{ ipa_domainadmin_password }}'' --hostname {{ inventory_hostname }}'
     - 'sed -i /etc/sssd/sssd.conf -e ''s/services.*/services = nss\, pam\, ssh\, sudo/''  '
     - 'sed -i /etc/sssd/sssd.conf -e ''s/ipa_dyndns_update/dyndns_update/''  '
     - 'sed -i /etc/sssd/sssd.conf -e ''/dyndns_update.*/ i\\dyndns_iface = eth0''  '
     - 'echo ''sudoers: files sss\n'' >> /etc/nsswitch.conf '
     - 'systemctl restart sssd'
     - 'dracut -f'
     - 'echo END'
     - 'poweroff'


# This is just too broken and unreliable.
#
#    power_state:
#      mode: poweroff
#      message: System ready for common role to be applied
#      timeout: 600

