
custom_script: |
    runcmd:
     #- 'hostname {{ inventory_hostname }}'
     #- 'hostname > /etc/hostname'
     #- '/usr/bin/nisdomainname {{ ipa_domain }}'
     #- 'echo NISDOMAIN={{ ipa_domain }} > /etc/sysconfig/network'
     #- '  '
     #- 'sed -i /etc/sssd/sssd.conf -e ''s/services.*/services = nss\, pam\, ssh\, sudo/''  '
     #- 'sed -i /etc/sssd/sssd.conf -e ''s/ipa_dyndns_update/dyndns_update/''  '
     #- 'sed -i /etc/sssd/sssd.conf -e ''/dyndns_update.*/ i\\dyndns_iface = eth0''  '
     #- 'echo ''sudoers: files sss\n'' >> /etc/nsswitch.conf '
     #- 'systemctl restart sssd'
     - 'dracut -f'
     - 'poweroff'
    final_message: YOU MUST NOW RUN THE ANSIBLE COMMON ROLE ON THIS SYSTEM

# Hostname should be getting set out of cloud init.
#     - '/root/postinstall.sh'
#     - 'systemctl restart NetworkManager'

# This is just too broken and unreliable.
#
#    power_state:
#      mode: poweroff
#      message: System ready for common role to be applied
#      timeout: 600

