
custom_script: |
    bootcmd:
    - 'hostname {{ inventory_hostname }}'
    - 'hostname > /etc/hostname'
    - '/usr/bin/nisdomainname {{ ipa_domain }}'
    - 'echo NISDOMAIN={{ ipa_domain }} > /etc/sysconfig/network'
    runcmd:
    - 'echo BEGIN'
    - '/usr/sbin/ipa-client-install -U --force-join --domain {{ ipa_domain }} --enable-dns-updates --mkhomedir --force-ntpd --no-dns-sshfp -p ''{{ ipa_domainadmin_username }}'' -w ''{{ ipa_domainadmin_password }}'' --hostname {{ inventory_hostname }}'
    - 'dracut -f'
    - 'echo END'
    - 'poweroff'


# This is just too broken and unreliable.
#
#    power_state:
#      mode: poweroff
#      message: System ready for common role to be applied
#      timeout: 600

