
# Update

# Make sure /home exists.
- name: Make /home
  become: true
  action: file path=/home owner=root group=wheel mode=0755 state=directory

# Install auth bits

- name: Install authentication libraries
  action: pkgng state=present name={{ item }}
  become: true
  with_items:
    - sssd
    - python27
    - openldap-client
    - vim
    - git
    - gmake
    - sudo
    - zsh
    - pam_mkhomedir

# ntp to internode.
# ssh + sssd user keys

- name: Base configurations
  become: true
  action: template src={{ item }} dest=/etc/{{ item }} owner=root group=wheel mode=0644
  with_items:
    - ntp.conf
    - ssh/sshd_config
    - nsswitch.conf
    - pam.d/sshd
    - pam.d/system

# Openldap certs
# openldap

- name: Usr configurations
  become: true
  action: template src={{ item }} dest=/usr/local/etc/{{ item }} owner=root group=wheel mode=0644
  with_items:
    - openldap/bh_ldap.crt
    - openldap/ldap.conf


# Configure SSSD

- name: Usr secure configurations
  become: true
  action: template src={{ item }} dest=/usr/local/etc/{{ item }} owner=root group=wheel mode=0600
  with_items:
    - sssd/sssd.conf
    - sudoers.d/bh_admins-sudo

- name: Ensure sssd enabled
  become: true
  action: lineinfile line='sssd_enable="YES"' dest=/etc/rc.conf

# sudo


- name: Install backup client
  action: pkgng state=present name={{ item }}
  become: true
  with_items:
    - amanda-client

# Amanda config expects /var/lib/amanda, but freebsd uses /var/db/amanda
- name: Make expected file paths
  become: true
  action: file path={{ item }} state=directory mode=0755 owner=root group=wheel
  with_items:
    - /var/lib
    - /var/log/audit
    - /srv
    - /opt

- name: Link amanda locations
  become: true
  action: file state=link src=/var/db/amanda dest=/var/lib/amanda

- name: Amanda secure configuration
  become: true
  template: src=amanda/{{ item }} dest=/var/db/amanda/{{ item }} owner=amanda group=amanda mode=0600
  with_items:
    - exclude
    - backup-pubkey.pem
    - .amandahosts


- name: Configure inetd service.
  become: true
  action: lineinfile dest="/etc/inetd.conf" line="amanda stream tcp6 nowait amanda /usr/local/libexec/amanda/amandad amandad -auth=bsdtcp amdump amindexd amidxtaped"

- name: Start inetd service.
  become: true
  action: lineinfile dest="/etc/rc.conf" line='inetd_enable="YES"'


