
- name: wait for vm
  action: wait_for port=22 delay=60

# We can probably configure IPA as a script in cloud init. We just need to generate the local machine password first.

- name: configure cloud init
  local_action: ovirt
    state=cloud_initialised
    instance_name={{ inventory_hostname }}
    user={{ ovirt_admin_username }}
    password={{ ovirt_admin_password }}
    url={{ ovirt_engine }}
    instance_hostname={{ inventory_hostname }}
    wait_action=true

- name: configure ipa client
  action: shell false

