
# We can probably configure IPA as a script in cloud init. We just need to generate the local machine password first.

- include_vars: postinst.yml

- name: Debug
  action: debug msg="{{ custom_script }}"

- name: configure cloud init
  local_action: ovirt
    state=cloud_initialised
    instance_name={{ inventory_hostname }}
    user={{ ovirt_admin_username }}
    password="{{ ovirt_admin_password }}"
    url={{ ovirt_engine }}
    instance_hostname={{ inventory_hostname }}
    wait_for_state=up
    custom_script="{{ custom_script }}"

