
- name: configure cloud init
  local_action: ovirt
    state=cloud_initialised
    instance_name={{ inventory_hostname }}
    user={{ ovirt_admin_username }}
    password="{{ ovirt_admin_password }}"
    url={{ ovirt_engine }}
    instance_hostname={{ inventory_hostname }}
    wait_for_state=down
    timeout=1800
    custom_script="{{ custom_script }}"

- name: create ks path
  sudo: yes
  action: file state=directory path=/var/www/html/ks/{{ inventory_hostname }}/
  delegate_to: "{{ item }}"
  with_items: groups.deployment_servers

- name: config template kickstart
  sudo: yes
  action: template src=ks.conf dest=/var/www/html/ks/{{ inventory_hostname }}/ks.conf
  delegate_to: "{{ item }}"
  with_items: groups.deployment_servers

#- name: config template cloud.cfg
#  sudo: yes
#  action: template src=cloud.cfg dest=/var/www/html/ks/{{ inventory_hostname }}/cloud.cfg
#  delegate_to: "{{ item }}"
#  with_items: groups.deployment_servers

### You need a way to get the machine MAC address so you can do per host boot menus

- name: config tftp menu
  sudo: yes
  action: template src=default dest=/var/lib/tftpboot/pxelinux.cfg/default
  delegate_to: "{{ item }}"
  with_items: groups.deployment_servers

- name: ovirt build instance
  local_action: ovirt
    state=started
    instance_name={{ inventory_hostname }}
    user={{ ovirt_admin_username }}
    password="{{ ovirt_admin_password }}"
    url={{ ovirt_engine }}
    wait_for_state=down
    timeout=7200

# Later we need a way to get the macaddr of the ovirt host.
# This way we can do per host config

# Some how wait til it's done then remove the ks?
- name: remove template kickstart
  sudo: yes
  action: file path=/var/www/html/ks/{{ inventory_hostname }}/ks.conf state=absent
  delegate_to: "{{ item }}"
  with_items: groups.deployment_servers

