
- include_vars: postinst.yml

# Only difference to template is the name
#    image=blank_pxe
- name: Ensure VM exists
  local_action: ovirt
    state=present
    instance_name={{ inventory_hostname }}
    user={{ ovirt_admin_username }}
    password="{{ ovirt_admin_password }}"
    url={{ ovirt_engine }}
    region={{ ovirt_dc }}
    zone={{ ovirt_cluster }}
    sdomain={{ ovirt_sdomain }}
    resource_type=template
    instance_type=server
    instance_cpus={{ ovirt_instance_cpus }}
    instance_mem={{ ovirt_instance_mem }}
    image=centos-{{ centos_version }}.{{ ipa_domain }}
    poll_timeout=3600
    wait_for_state=down
  notify:
    - configure cloud init

#  notify:
#    - create ks path
#    - config template kickstart
#    - config tftp menu
#    - ovirt build instance
##    - remove template kickstart

- meta: flush_handlers

# This will PXE boot, build and STOP the instance
- name: ovirt launch instance
  local_action: ovirt
    state=started
    instance_name={{ inventory_hostname }}
    user={{ ovirt_admin_username }}
    password="{{ ovirt_admin_password }}"
    url={{ ovirt_engine }}
    wait_for_state=up
    timeout=7200

