
# Add the repo definitions

- name: add copr repo
  sudo: yes
  action: template src=firstyear-ds-copr.repo dest=/etc/yum.repos.d/firstyear-ds-copr.repo owner=root group=root mode=0644

- name: install directory server
  sudo: yes
  action: yum name={{ item }} state=present
  with_items:
    - 389-ds-base
    - python2-rest389
    - python2-idm389
    - freeradius
    - freeradius-utils
    - freeradius-ldap
    - ldapvi

- name: configure auth master firewall
  sudo: yes
  firewalld: zone=internal permanent=true state=enabled service={{ item }} immediate=true
  with_items:
    - ldap
    - ldaps
  when: "'linode_servers' not in group_names"

- name: configure limited auth master firewall
  sudo: yes
  firewalld: zone=internal permanent=yes state=enabled immediate=yes rich_rule='rule family="ipv6" source address="{{ item[1] }}" service name="{{ item[0] }}" accept'
  with_nested:
    - [ 'ldap', 'ldaps' ]
    - [ '2001:44b8:2155:2c00::/56', '2a01:7e00::f03c:91ff:fe84:9e3e', '2400:8901::f03c:91ff:fe98:4593', '2a01:7e00::f03c:91ff:feae:5d82' ]
  when: "'linode_servers' in group_names"

- name: enable all auth services
  sudo: yes
  action: service name=dirsrv@blackhats state=started enabled=yes

- include: radius.yml
  when: "'linode_servers' not in group_names"


##########################################################
#
# What next! 
#
# Get setup.inf from tokiha /root/setup.inf
# Now you want to install with:
#
# setup-ds.pl --file=setup.inf --silent --debug
# 
# Now apply the ldif setup.ldif also on tokiha
# 
# Now on the ldap server make the cert request.
# Make the pwdfile and pin.txt. Remember Internal (Software) Token:
#
# certutil -d . -N -f pwdfile.txt
#
# certutil -d . -R -a -o ldap-linode.blackhats.net.au.csr -f pwdfile.txt -s "CN=ldap-linode.blackhats.net.au,O=Blackhats,L=Brisbane,ST=Queensland,C=AU" -v 24 -8 .......
# Sign it
# certutil -C -d . -v 24 -i /home/william/ldap-linode.blackhats.net.au.csr -a -o /home/william/ldap-linode.blackhats.net.au.crt -c BH_LDAP_CA
# Now add
#  certutil -A -d . -n "BH_LDAP_CA" -t "C,C,C" -i /etc/pki/tls/certs/bh_ldap.crt
#  certutil -A -d . -n "Server-Cert" -t ",," -i /tmp/ldap-linode.blackhats.net.au.crt
# 
# Now apply the changelog enable ldif
# Then add the agreements
#
#


