
- name: Resize /var for content
  become: true
  lvol: vg=vg00 lv=var_lv size=10g
  notify:
    - resize xfs
    - remount xfs
  ignore_errors: yes

- meta: flush_handlers

- name: Install mirror software
  become: true
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - rsync
    - createrepo
    - tftp
    - tftp-server
    - syslinux-tftpboot
    - ipxe-bootimgs
    - squid
    - nfs-utils

- name: deploy configuration
  become: true
  action: template src={{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - squid/squid.conf
    - firewalld/services/squid.xml
    - exports
    - sysconfig/nfs

- name: Configure mirror paths
  become: true
  action: file state=directory path={{ item }}
  with_items:
   - /var/lib/tftpboot/pxelinux.cfg/
   - /var/lib/tftpboot/openbsd/5.8/amd64/
   - /var/www/html/ks/
   - /var/www/html/pub/centos/{{ centos_version }}/os/x86_64/images/pxeboot/
   - /var/www/html/pub/freebsd/10.3/amd64/

- name: kickstart squid started
  become: true
  action: service name=squid.service enabled=yes state=started

- name: kickstart httpd started
  become: true
  action: service name=httpd.service enabled=yes state=started

- name: kickstart tftpd started
  become: true
  action: service name=tftp.socket enabled=yes state=started

- name: kickstart nfs started
  become: true
  action: service name=nfs-server.service enabled=yes state=started

# This is too fiddly to make work, so you may need to restart by hand :( 
- name: reload firewalld (Else squid breaks)
  become: true
  action: service name=firewalld.service enabled=yes state=restarted

- name: config mirror firewalld
  become: true
  firewalld: service={{ item }} zone=internal permanent=yes state=enabled immediate=yes
  with_items:
    - http
    - tftp
    - squid
    - nfs
    - mountd
    - rpc-bind

- name: nfsv3 firewalld
  become: true
  firewalld: port=20049-20052/tcp zone=internal permanent=yes state=enabled immediate=yes

- name: nfsv3 firewalld
  become: true
  firewalld: port=20049-20052/udp zone=internal permanent=yes state=enabled immediate=yes

- name: nfsv3 firewall sunrpc
  become: true
  firewalld: port=111/tcp zone=internal permanent=yes state=enabled immediate=yes

- name: nfsv3 firewall sunrpc
  become: true
  firewalld: port=111/udp zone=internal permanent=yes state=enabled immediate=yes

- name: sync pxeboot mirror
  become: true
  #action: shell rsync -az --exclude='*.iso' rsync://{{ centos_mirror }}/centos/{{ centos_version }}/os/x86_64/ /var/www/html/pub/centos/{{ centos_version }}/os/x86_64/
  action: shell rsync -avz --exclude='*.iso' rsync://{{ centos_mirror }}/centos/{{ centos_version }}/os/x86_64/images/pxeboot/ /var/www/html/pub/centos/{{ centos_version }}/os/x86_64/images/pxeboot/
  #delegate_to: "{{ item }}"
  #with_items: groups.deployment_servers

- name: sync treeinfo
  become: true
  action: shell rsync -avz --exclude='*.iso' rsync://{{ centos_mirror }}/centos/{{ centos_version }}/os/x86_64/.treeinfo /var/www/html/pub/centos/{{ centos_version }}/os/x86_64/.treeinfo

- name: sync LiveOS
  become: true
  action: shell rsync -avz --exclude='*.iso' rsync://{{ centos_mirror }}/centos/{{ centos_version }}/os/x86_64/LiveOS/ /var/www/html/pub/centos/{{ centos_version }}/os/x86_64/LiveOS/

#- name: sync update mirror
#  become: true
#  action: shell rsync -az rsync://{{ centos_mirror }}/centos/{{ centos_version }}/updates/x86_64/ /var/www/html/pub/centos/{{ centos_version }}/updates/x86_64/
#  delegate_to: "{{ item }}"
#  with_items: groups.deployment_servers
#
#- name: sync extras mirror
#  become: true
#  action: shell rsync -az rsync://{{ centos_mirror }}/centos/{{ centos_version }}/extras/x86_64/ /var/www/html/pub/centos/{{ centos_version }}/extras/x86_64/
#  delegate_to: "{{ item }}"
#  with_items: groups.deployment_servers
#
#- name: sync epel mirror
#  become: true
#  action: shell rsync -az --exclude='debug/*' rsync://{{ centos_mirror }}/epel/{{ centos_version }}/x86_64/ /var/www/html/pub/epel/{{ centos_version }}/x86_64/
#  delegate_to: "{{ item }}"
#  with_items: groups.deployment_servers

- name: sync Openbsd PXE mirror
  become: true
  action: shell rsync -az rsync://{{ centos_mirror }}/openbsd/5.8/amd64/{{ item }} /var/lib/tftpboot/openbsd/5.8/amd64/{{ item }}
  with_items:
    - pxeboot
    - bsd
    - bsd.mp
    - bsd.rd

- name: sync FreeBSD PXE mirror
  become: true
  action: shell rsync -az rsync://{{ centos_mirror }}/freebsd/releases/amd64/amd64/ISO-IMAGES/10.3/{{ item }} /var/www/html/pub/freebsd/10.3/amd64/{{ item }}
  with_items:
    - FreeBSD-10.3-RELEASE-amd64-bootonly.iso


# http://freebsd.so14k.com/freebsd9_pxe.shtml

