
- name: Resize /var for content
  sudo: yes
  lvol: vg=vg00 lv=var_lv size=10g
  notify:
    - resize xfs
    - remount xfs
  ignore_errors: yes

- meta: flush_handlers

- name: Install mirror software
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - rsync
    - createrepo
    - tftp
    - tftp-server
    - syslinux-tftpboot
    - ipxe-bootimgs
    - squid

- name: deploy configuration
  sudo: yes
  action: template src={{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - squid/squid.conf
    - firewalld/services/squid.xml

- name: Configure mirror paths
  sudo: yes
  action: file state=directory path={{ item }}
  with_items:
   - /var/lib/tftpboot/pxelinux.cfg/
   - /var/lib/tftpboot/openbsd/5.8/amd64/
   - /var/www/html/ks/
   - /var/www/html/pub/centos/{{ centos_version }}/os/x86_64/images/pxeboot/

- name: kickstart squid started
  sudo: yes
  action: service name=squid.service enabled=yes state=started

- name: kickstart httpd started
  sudo: yes
  action: service name=httpd.service enabled=yes state=started

- name: kickstart tftpd started
  sudo: yes
  action: service name=tftp.socket enabled=yes state=started

# This is too fiddly to make work, so you may need to restart by hand :( 
#- name: reload firewalld (Else squid breaks)
#  sudo: yes
#  action: service name=firewalld.service enabled=yes state=reloaded

- name: config mirror firewalld
  sudo: yes
  firewalld: service={{ item }} zone=internal permanent=yes state=enabled immediate=yes
  with_items:
    - http
    - tftp
    - squid

- name: sync pxeboot mirror
  sudo: yes
  #action: shell rsync -az --exclude='*.iso' rsync://{{ centos_mirror }}/centos/{{ centos_version }}/os/x86_64/ /var/www/html/pub/centos/{{ centos_version }}/os/x86_64/
  action: shell rsync -avz --exclude='*.iso' rsync://{{ centos_mirror }}/centos/{{ centos_version }}/os/x86_64/images/pxeboot/ /var/www/html/pub/centos/{{ centos_version }}/os/x86_64/images/pxeboot/
  #delegate_to: "{{ item }}"
  #with_items: groups.deployment_servers

- name: sync treeinfo
  sudo: yes
  action: shell rsync -avz --exclude='*.iso' rsync://{{ centos_mirror }}/centos/{{ centos_version }}/os/x86_64/.treeinfo /var/www/html/pub/centos/{{ centos_version }}/os/x86_64/.treeinfo

- name: sync LiveOS
  sudo: yes
  action: shell rsync -avz --exclude='*.iso' rsync://{{ centos_mirror }}/centos/{{ centos_version }}/os/x86_64/LiveOS/ /var/www/html/pub/centos/{{ centos_version }}/os/x86_64/LiveOS/

#- name: sync update mirror
#  sudo: yes
#  action: shell rsync -az rsync://{{ centos_mirror }}/centos/{{ centos_version }}/updates/x86_64/ /var/www/html/pub/centos/{{ centos_version }}/updates/x86_64/
#  delegate_to: "{{ item }}"
#  with_items: groups.deployment_servers
#
#- name: sync extras mirror
#  sudo: yes
#  action: shell rsync -az rsync://{{ centos_mirror }}/centos/{{ centos_version }}/extras/x86_64/ /var/www/html/pub/centos/{{ centos_version }}/extras/x86_64/
#  delegate_to: "{{ item }}"
#  with_items: groups.deployment_servers
#
#- name: sync epel mirror
#  sudo: yes
#  action: shell rsync -az --exclude='debug/*' rsync://{{ centos_mirror }}/epel/{{ centos_version }}/x86_64/ /var/www/html/pub/epel/{{ centos_version }}/x86_64/
#  delegate_to: "{{ item }}"
#  with_items: groups.deployment_servers

- name: sync Openbsd PXE mirror
  sudo: yes
  action: shell rsync -az rsync://{{ centos_mirror }}/openbsd/5.8/amd64/{{ item }} /var/lib/tftpboot/openbsd/5.8/amd64/{{ item }}
  with_items:
    - pxeboot
    - bsd
    - bsd.mp
    - bsd.rd

