
- include_vars: main.yml

- name: Install postgis software
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
   - postgresql-server
   - postgis
   - postgresql
   - python-psycopg2
  notify:
    - initdb

- meta: flush_handlers

- name: Configure HBA
  sudo: yes
  template: src=pg_hba.conf dest=/var/lib/pgsql/data/pg_hba.conf owner=postgres group=postgres mode=0600
  notify:
    - restart pgsql

- name: Enable pgsql
  sudo: yes
  service: name=postgresql enabled=yes state=started

- meta: flush_handlers

- name: Create postgis database instances
  sudo: yes
  sudo_user: postgres
  action: postgresql_db name='{{ item.name }}'
  with_items: postgis_instances

- name: Add postgis extensions
  sudo: yes
  sudo_user: postgres
  postgresql_ext: name=postgis db='{{ item.name }}'
  with_items: postgis_instances

- name: Create postgres roles to match auth
  sudo: yes
  sudo_user: postgres
  action: postgresql_user name='{{ item.1 }}' db='{{ item.0.name }}' priv=ALL state=present
  with_subelements:
    - postgis_instances
    - authorised

- name: Postgres firewalld
  sudo: yes
  action: firewalld zone=internal permanent=true state=enabled service=postgresql
  notify:
    - reload firewalld

- name: Create backups dir
  sudo: yes
  action: file state=directory path='/var/backups/' owner='postgres' group='postgres' mode=0750

- name: Cron backup job
  sudo: yes
  action: cron name="Backup postgis insts" minute="10" hour="23" job="/usr/bin/pg_dump {{ item.name }} > /var/backups/{{ item.name }}.sql" user="postgres"
  with_items: postgis_instances


