
- name: Install mail software
  sudo: yes
  action: yum name={{ item }} state=present
  with_items:
    - postfix
    - postgrey
    - dovecot
    - dovecot-pigeonhole
    - clamav-milter
    - spamass-milter
    - spamass-milter-postfix
    - clamav-milter-systemd
    - clamav-server-systemd
    - clamav-scanner
    - clamav-scanner-systemd
    - spamassassin
    - opendkim

- name: Create vmail user
  sudo: yes
  action: user name=vmail uid=1000

- name: Alter postfix user
  sudo: yes
  action: user name=postfix append=yes groups=clamilt,sa-milt

- name: Alter clamscan user
  sudo: yes
  action: user name=clamscan append=yes groups=clamilt

- name: Create smtpd link
  sudo: yes
  action: file src=/usr/lib/systemd/system/clamd@.service dest=/etc/systemd/system/clamd@clamsmtp.service state=link

- name: config email firewalld
  sudo: yes
  firewalld: service={{ item }} zone=internal permanent=yes state=enabled immediate=yes
  with_items:
    - smtp
    - imaps

- name: config email ports firewalld
  sudo: yes
  firewalld: port={{ item }} zone=internal permanent=yes state=enabled immediate=yes
  with_items:
    - 143/tcp
    - 465/tcp
    - 587/tcp

### Now actually do some configuration.

# Config the email storage. Make sure the lvol is big enough.
- name: Resize /var for content
  sudo: yes
  lvol: vg=vg00 lv=var_lv size=10g
  notify:
    - resize xfs
    - remount xfs
  when: "'linode_servers' not in group_names"

# Config the email storage. Make sure the lvol is big enough.
- name: Resize /var/log for logs
  sudo: yes
  lvol: vg=vg00 lv=var_log_lv size=6g
  notify:
    - resize xfs
    - remount xfs
  when: "'linode_servers' not in group_names"

# Make /var/lib/dovecot +x

- name: Create clamscan log dir
  sudo: yes
  action: file path=/var/log/clamd.scan state=directory mode=0755 owner=clamscan group=clamscan
# Create SSL keys? How do we best manage this with IPA?

- name: Deploy certificates
  sudo: yes
  action: command ipa-getcert request -k /etc/pki/tls/private/mail.firstyear.id.au.key -f /etc/pki/tls/certs/mail.firstyear.id.au.crt -I mail.firstyear.id.au -g 4096 -w
  ignore_errors: yes

# Deploy all the configs.

- name: Deploy dovecot configurations
  sudo: yes
  template: src=etc/dovecot/{{ item }} dest=/etc/dovecot/{{ item }} owner=root group=root mode=0644
  with_items:
    - conf.d/10-auth.conf
    - conf.d/10-mail.conf
    - conf.d/10-master.conf
    - conf.d/15-lda.conf
    - conf.d/20-imap.conf
    - conf.d/90-quota.conf
    - conf.d/auth-ldap.conf.ext
    - conf.d/90-sieve.conf
    - conf.d/90-plugin.conf
    - conf.d/10-ssl.conf
    - dovecot.conf
    - dovecot-ldap.conf.ext
  notify: restart dovecot

- name: Deploy postfix hash configurations
  sudo: yes
  template: src=etc/postfix/{{ item }} dest=/etc/postfix/{{ item }} owner=root group=root mode=0644
  with_items:
    - transport
    - recipientmap
  notify:
    - postmap
    - restart postfix

- name: Deploy postfix configurations
  sudo: yes
  template: src=etc/postfix/{{ item }} dest=/etc/postfix/{{ item }} owner=root group=root mode=0644
  with_items:
    - main.cf
    - master.cf
    - postgrey_whitelist_clients.local
  notify: restart postfix


## When some things like transport are deployed, rehash them

- name: Deploy clam milter config
  sudo: yes
  template: src=etc/mail/clamav-milter.conf dest=/etc/mail/clamav-milter.conf owner=root group=root mode=0644
  notify: restart clamav-milter

- name: Deploy clam config
  sudo: yes
  template: src=etc/clamd.d/clamsmtp.conf dest=/etc/clamd.d/clamsmtp.conf owner=root group=root mode=0644
  notify: restart clamd

- name: Deploy spamassassin config
  sudo: yes
  template: src=etc/mail/spamassassin/local.cf dest=/etc/mail/spamassassin/local.cf owner=root group=root mode=0644

- name: Deploy opendkim config
  sudo: yes
  template: src={{ item }} dest=/{{ item }} owner=root group=root mode=0644
  with_items:
    - etc/opendkim.conf
    - etc/opendkim/KeyTable
    - etc/opendkim/SigningTable
    - etc/opendkim/TrustedHosts

- name: Deploy mail scripts
  sudo: yes
  template: src={{ item }} dest=/root/{{ item }} owner=root group=root mode=0750
  with_items:
    - learn.sh
    - mailbox-rollover.sh


# Need a notify to restart bits ...

## Still need to add clamav and spamassasin bits.

- name: Enable mail services
  sudo: yes
  service: name={{ item }} state=started enabled=yes
  with_items:
    - opendkim
    - spamass-milter
    - clamd@clamsmtp
    - clamav-milter
    - postfix
    - postgrey
    - dovecot

