
- name: postmap
  sudo: yes
  shell: postmap /etc/postfix/{{ item }}
  with_items:
    - transport
    - recipientmap
    - relay_recipients

- name: restart postfix
  sudo: yes
  service: name={{ item }} state=restarted
  with_items:
    - postgrey
    - postfix

