
- name: Install bind
  become: yes
  action: yum name=bind state=present

# Deploy the configs here
- name: deploy configs
  become: yes
  action: template src={{ item }} dest=/etc/{{ item }} owner=root group=named mode=0640
  with_items:
    - named.conf

# We need to make sure the shitty version of named isn't starting.
- name: Disable dns pkcs11 services
  become: yes
  action: service name=named-pkcs11 state=stopped enabled=no
  ignore_errors: yes

- name: Enable dns services
  become: yes
  action: service name=named state=started enabled=yes

- name: config dns firewall
  become: yes
  action: firewalld service=dns zone=internal permanent=yes state=enabled immediate=yes

# DNS master also acts as the CA master now.

- name: Install certbot
  become: true
  action: package name={{ item }} state=present
  with_items:
    - certbot

- name: deploy authhook
  become: yes
  action: template src={{ item }} dest=/root/{{ item }} owner=root group=named mode=0750
  with_items:
    - manual-hook.sh
    - request.sh
    - renew.sh


###
# https_proxy=http://proxy-bne1.net.blackhats.net.au:3128 certbot certonly --staging -m william@blackhats.net.au --manual --preferred-challenges=dns
#
# https_proxy=http://proxy-bne1.net.blackhats.net.au:3128 certbot certonly --staging -m william@blackhats.net.au --manual --preferred-challenges=dns --manual-public-ip-logging-ok --agree-tos -d fy.cloud.blackhats.net.au
#

