
- name: Install amanda software
  sudo: yes
  package: name={{ item }} state=present
  with_items:
    - amanda-client
  tags:
    - amanda

- name: Configure amanda service socket
  sudo: yes
  service: name=amanda.socket enabled=yes state=started
  tags:
    - amanda

- name: Configure Amanda allowed hosts
  sudo: yes
  template: src=amanda/amandahosts dest=/var/lib/amanda/.amandahosts owner=amandabackup group=disk mode=0600
  tags:
    - amanda

- name: Configure Amanda public key
  sudo: yes
  template: src=amanda/backup-pubkey.pem dest=/var/lib/amanda/backup-pubkey.pem owner=amandabackup group=disk mode=0600
  tags:
    - amanda

# This should touch the file instead?
- name: Ensure excludes
  sudo: yes
  file: path=/var/lib/amanda/exclude state=touch owner=amandabackup group=disk mode=0600
  tags:
    - amanda

# Don't open amanda up to all
- name: Configure amanda firewall
  sudo: yes
  firewalld: service=amanda-client zone=internal permanent=yes state=disabled immediate=yes
  tags:
    - amanda

- name: Configure amanda specific firewall
  sudo: yes
  firewalld: zone=internal permanent=yes state=enabled immediate=yes rich_rule='rule family="ipv6" source address="2001:44b8:2155:2c11:5054:ff:feba:574" port port="10080" protocol="tcp" accept'
  #rule family="ipv6" source address="2001:44b8:2155:2c11:5054:ff:feba:574" service name="amanda-client" accept
  tags:
    - amanda
  # Is there a way to generate these ips out of the amanda hosts?
  #with_items:
  #  - 2001:44b8:2155:2c11:5054:ff:feba:574
