
- name: install kdump
  sudo: yes
  package: name=kexec-tools state=present

- name: deploy kdump configuration
  sudo: yes
  template: src=kdump/kdump.conf dest=/etc/kdump.conf owner=root group=root mode=0644
  notify:
    - restart kdump

- name: ensure kdump running
  sudo: yes
  service: name=kdump state=started enabled=yes
  ignore_errors: yes

