

- name: Install default software
  sudo: yes
  package: name={{ item }} state=present
  with_items:
    - abrt-cli
    - audit
    - bind-utils
    - gdisk
    - git
    - iotop
    - nmap
    - mlocate
    - postfix
    - screen
    - strace
    - vim
    - yum-utils
    - zsh
    # Needed for ansible
    - libselinux-python
    - python-firewall

- name: Install HP software
  sudo: yes
  package: name={{ item }} state=present
  with_items:
    - hponcfg
    - hpacucli
    - hpvca
    - lm_sensors
  when: "'hp_servers_disabled' in group_names"
