
# Create the docker volume for squid
- name: Create docker volume for squid cache
  become: true
  docker_volume:
    name: squid_cache

- name: Create docker volume for squid logs
  become: true
  docker_volume:
    name: squid_logs

# Make the image up to daterer
#  notify a restart of docker
# - name: Pull squid image
#   become: true
#   docker_image:
#     name: registry.blackhats.net.au/squid:latest
#     pull: yes
#     force: yes
#     state: present

# Make sure the container exists with restart-always
- name: Create squid container
  become: true
  docker_container:
    name: squid
    image: registry.blackhats.net.au/squid:latest
    volumes:
      - "squid_logs:/var/log"
      - "squid_cache:/var/spool/squid"
    ports:
      - "3128:3128"
    restart_policy: always
    # Apparently this pulls the latest image always?
    pull: yes


- name: Setup the lets encrypt renewal
  become: true
  # ???

- name: Create docker volume for nextcloud_db
  become: true
  docker_volume:
    name: nextcloud_db

- name: Create docker volume for nextcloud
  become: true
  docker_volume:
    name: nextcloud

# docker network create test-net
- name: Create private DB network
  become: true
  docker_network:
    name: nextcloud_net

# docker run -v pgdata:/var/lib/postgresql/data  --name pgtest --network test-net postgres:11
- name: Create a pgsql instance for nextcloud
  become: true
  docker_container:
    name: nextcloud_db
    image: postgres:11
    volumes:
      - "nextcloud_db:/var/lib/postgresql/data"
    networks:
      - name: nextcloud_net
    restart_policy: always
    # Apparently this pulls the latest image always?
    pull: yes

- name: Create nextcloud-haproxy
  become: true
  docker_container:
    name: nextcloud-haproxy
    image: nextcloud-haproxy:latest
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
    networks:
      - name: nextcloud_net
    restart_policy: always
    ports:
      - "443:443"
    # Apparently this pulls the latest image always?
    pull: yes

# docker run --network test-net -p 8080:80 -v nextcloud:/var/www/html nextcloud:latest
- name: Create nextcloud
  become: true
  docker_container:
    name: nextcloud
    image: nextcloud:latest
    volumes:
      - "nextcloud:/var/www/html"
    networks:
      - name: nextcloud_net
    restart_policy: always
    # Apparently this pulls the latest image always?
    pull: yes


