
# Create the docker volume for squid
- name: Create docker volume for squid cache
  become: true
  docker_volume:
    name: squid_cache

- name: Create docker volume for squid logs
  become: true
  docker_volume:
    name: squid_logs

# Make the image up to daterer
#  notify a restart of docker
# - name: Pull squid image
#   become: true
#   docker_image:
#     name: registry.blackhats.net.au/squid:latest
#     pull: yes
#     force: yes
#     state: present

# Make sure the container exists with restart-always
- name: Create squid container
  become: true
  docker_container:
    name: squid
    image: registry.blackhats.net.au/squid:latest
    volumes:
      - "squid_logs:/var/log"
      - "squid_cache:/var/spool/squid"
    ports:
      - "3128:3128"
    restart_policy: always
    # Apparently this pulls the latest image always?
    pull: yes


# - name: Setup the lets encrypt renewal
#   become: true
#   # ???

- name: Create docker volume for nextcloud_db
  become: true
  docker_volume:
    name: nextcloud_db

- name: Create docker volume for nextcloud
  become: true
  docker_volume:
    name: nextcloud

# docker network create test-net
- name: Create private DB network
  become: true
  docker_network:
    name: nextcloud_net

# docker run -v pgdata:/var/lib/postgresql/data  --name pgtest --network test-net postgres:11
- name: Create a pgsql instance for nextcloud
  become: true
  docker_container:
    name: nextcloud_db
    image: postgres:11
    volumes:
      - "nextcloud_db:/var/lib/postgresql/data"
    networks:
      - name: nextcloud_net
    restart_policy: always
    # Apparently this pulls the latest image always?
    pull: yes

# docker run --network test-net -p 8080:80 -v nextcloud:/var/www/html nextcloud:latest
#
# docker exec -i -t -u www-data nextcloud php occ upgrade
# docker exec -i -t -u www-data nextcloud php occ maintenance:mode --on
- name: Create nextcloud
  become: true
  docker_container:
    name: nextcloud
    image: nextcloud:latest
    volumes:
      - "nextcloud:/var/www/html"
    networks:
      - name: nextcloud_net
    restart_policy: always
    # Apparently this pulls the latest image always?
    pull: yes

- name: Create nextcloud-haproxy
  become: true
  docker_container:
    name: haproxy
    image: registry.blackhats.net.au/haproxy:latest
    volumes:
      - "/etc/certbot:/etc/certbot"
    networks:
      - name: nextcloud_net
    restart_policy: always
    env:
      HAPROXY_TARGET: nextcloud
      HAPROXY_HOSTNAME: nextcloud.blackhats.net.au
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    # Apparently this pulls the latest image always?
    pull: yes
  tags:
    - haproxy



- name: Create docker volume for samba ad-dc
  become: true
  docker_volume:
    name: samba_rwdc

# Make sure the container exists with restart-always
- name: Create samba_rwdc container
  become: true
  docker_container:
    name: samba_rwdc
    image: registry.blackhats.net.au/samba_rwdc:latest
    volumes:
      - "samba_rwdc:/var/lib/samba"
    ports:
      - "389:389"
      - "636:636"
    restart_policy: always
    pull: yes


# SAMBA
# So it's not docker, but this is the config and avahi setup.

- name: Ensure timemachine user
  become: yes
  user: name=timemachine group=users uid=1001
  tags:
    - samba

- name: Deploy samba config
  become: yes
  template: src=samba/smb.conf dest=/etc/samba/smb.conf owner=root group=root mode=0600
  tags:
    - samba

# - name: Deploy timemachine quota
#   become: yes
#   template: src=samba/com.apple.TimeMachine.quote.plist dest=/var/data/backup/timemachine/.com.apple.TimeMachine.quote.plist owner=timemachine group=timemachine mode=0600

- name: Ensure samba active
  become: yes
  service: name=smb enabled=yes
  tags:
    - samba



