
- name: deploy ca.certs
  become: yes
  ignore_errors: yes
  action: copy src=../../templates/docker/certs.d/registry.blackhats.net.au dest=/etc/docker/certs.d/

- name: Deploy the setup cert script
  template: src=base/scripts/{{ item }} dest=/etc/docker/certs.d/registry.blackhats.net.au/{{ item }} owner=root group=root mode=0750
  become: yes
  with_items:
    - docker-csr.sh

- include: apps_amber.yml
  when: "'amber' in inventory_hostname"

- include: manage_lazuli.yml
  when: "'lazuli' in inventory_hostname"

