
- name: Create lifx controller
  become: true
  docker_container:
    name: lifx
    image: firstyear/lifx:latest
    restart_policy: always
    pull: yes
    user: 1005:1005
    memory: 400M
  tags:
    - docker
    - lifx

- name: Create unifi data volume
  become: true
  docker_volume:
    name: unifi_data
  tags:
    - docker
    - unifi

- name: Create unifi log volume
  become: true
  docker_volume:
    name: unifi_log
  tags:
    - docker
    - unifi

## docker create --restart always --name unifi --network host -v unifi_data:/unifi/data -v unifi_log:/unifi/log -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro -e TZ=Australia/Brisbane jacobalberty/unifi:5.9

- name: Create unifi controller
  become: true
  docker_container:
    name: unifi
    image: jacobalberty/unifi:stable
    # can ssh to aps with ubnt:ubnt and ruN;
    # mca-cli
    # set-inform http://<host_ip>:8080/inform
    # set-inform http://172.24.10.19:8080/inform
    # set-inform http://unifi.net.blackhats.net.au:8080/inform
    network_mode: host
    volumes:
      - "unifi_data:/unifi/data"
      - "unifi_log:/unifi/log"
      - "/etc/localtime:/etc/localtime:ro"
    # env:
    #   TZ: "Australia/Brisbane"
    restart_policy: always
    pull: yes
  tags:
    - docker
    - unifi

- name: Create kanidm radiusd volume
  become: true
  docker_volume:
    name: kanidm_radiusd
  tags:
    - docker
    - radius
    - kanidm

- name: Create kanidm radiusd controller
  become: true
  docker_container:
    name: kanidm_radiusd
    image: kanidm/radius:latest
    ports:
      - 1812:1812
      - 1812:1812/udp
      - 1813:1813
      - 1813:1813/udp
    volumes:
      - "kanidm_radiusd:/data"
    restart_policy: always
    env:
      DEBUG: "true"
    pull: yes
  tags:
    - docker
    - kanidm
    - radius


