
- name: Create registry volume
  become: true
  docker_volume:
    name: registry
  tags:
    - docker

- name: Create registry
  become: true
  docker_container:
    name: registry
    image: registry:2
    volumes:
      - "registry:/var/lib/registry"
    ports:
      - "443:443"
    env:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /var/lib/registry/certs/docker.crt
      REGISTRY_HTTP_TLS_KEY: /var/lib/registry/certs/docker.key
      REGISTRY_HTTP_TLS_CLIENTCAS: " - /var/lib/registry/certs/ca.crt"
    restart_policy: always
    pull: yes
  tags:
    - docker


- name: Create lifx controller
  become: true
  docker_container:
    name: lifx
    image: registry.blackhats.net.au/lifx:latest
    restart_policy: always
    pull: yes
  tags:
    - docker


- name: Create unifi data volume
  become: true
  docker_volume:
    name: unifi_data
  tags:
    - docker

- name: Create unifi log volume
  become: true
  docker_volume:
    name: unifi_log
  tags:
    - docker

## docker create --restart always --name unifi --network host -v unifi_data:/unifi/data -v unifi_log:/unifi/log -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro -e TZ=Australia/Brisbane jacobalberty/unifi:5.9

- name: Create unifi controller
  become: true
  docker_container:
    name: unifi
    image: jacobalberty/unifi:stable
    # can ssh to aps with ubnt:ubnt and ruN;
    # mca-cli
    # set-inform http://<host_ip>:8080/inform
    # set-inform http://172.24.10.19:8080/inform
    # set-inform http://unifi.net.blackhats.net.au:8080/inform
    network_mode: host
    volumes:
      - "unifi_data:/unifi/data"
      - "unifi_log:/unifi/log"
      - "/etc/localtime:/etc/localtime:ro"
    # env:
    #   TZ: "Australia/Brisbane"
    restart_policy: always
    pull: yes
  tags:
    - docker


- name: Create radiusd pki volume
  become: true
  docker_volume:
    name: radiusd_pki
  tags:
    - docker

- name: Create radiusd controller
  become: true
  docker_container:
    name: radiusd
    image: registry.blackhats.net.au/radiusd:latest
    ports:
      - 1812:1812
      - 1812:1812/udp
      - 1813:1813
      - 1813:1813/udp
    volumes:
      - "radiusd_pki:/etc/pki/radius"
    restart_policy: always
    pull: yes
  tags:
    - docker



