
- name: Create micd data volume
  become: true
  docker_volume:
    name: micd_data
  tags:
    - docker
    - micd

- name: Create micd controller
  become: true
  docker_container:
    name: micd
    image: firstyear/micd:latest
    restart_policy: always
    pull: yes
    user: 1006:1006
    memory: 400M
    network_mode: host
    volumes:
      - "micd_data:/data"
    env:
      RUST_LOG: "actix=info,micd=info,mic=info"
      # RUST_LOG: "actix=debug,micd=debug,mic=debug"
    log_driver: journald
  tags:
    - docker
    - micd

- name: Create lifx network
  become: true
  docker_network:
    name: lifx_net
  tags:
    - docker
    - lifx

- name: Create lifx controller
  become: true
  docker_container:
    name: lifx
    image: firstyear/lifx:latest
    restart_policy: always
    purge_networks: yes
    networks:
      - name: lifx_net
    pull: yes
    user: 1005:1005
    memory: 400M
    ports:
      - "8081:8081"
    env:
      RUST_LOG: "actix=debug,lifx=debug"
    log_driver: journald
  tags:
    - docker
    - lifx

- name: Create unifi data volume
  become: true
  docker_volume:
    name: unifi_data
  tags:
    - docker
    - unifi

- name: Create unifi log volume
  become: true
  docker_volume:
    name: unifi_log
  tags:
    - docker
    - unifi

## docker create --restart always --name unifi --network host -v unifi_data:/unifi/data -v unifi_log:/unifi/log -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro -e TZ=Australia/Brisbane jacobalberty/unifi:5.9

- name: Create unifi controller
  become: true
  docker_container:
    name: unifi
    image: jacobalberty/unifi:stable
    # can ssh to aps with ubnt:ubnt and ruN;
    # mca-cli
    # set-inform http://<host_ip>:8080/inform
    # set-inform http://172.24.10.19:8080/inform
    # set-inform http://unifi.net.blackhats.net.au:8080/inform
    network_mode: host
    volumes:
      - "unifi_data:/unifi/data"
      - "unifi_log:/unifi/log"
      - "/etc/localtime:/etc/localtime:ro"
    # env:
    #   TZ: "Australia/Brisbane"
    restart_policy: always
    pull: yes
    log_driver: journald
  tags:
    - docker
    - unifi

- name: Create kanidm radiusd volume
  become: true
  docker_volume:
    name: kanidm_radiusd
  tags:
    - docker
    - radius
    - kanidm

# This is in network mode host to allow ipv6 contact to kandim, but we could try the ipv6nat
# support ....
- name: Create kanidm radiusd controller
  become: true
  docker_container:
    name: kanidm_radiusd
    image: kanidm/radius:latest
    ports:
      - 1812:1812
      - 1812:1812/udp
      - 1813:1813
      - 1813:1813/udp
    network_mode: host
    volumes:
      - "kanidm_radiusd:/data"
    restart_policy: always
    env:
      DEBUG: "true"
    log_driver: journald
    pull: yes
  tags:
    - docker
    - kanidm
    - radius


