- name: Create uv1-uv10network (mgmt)
  become: true
  docker_network:
    name: dk_v10_mgmt
    enable_ipv6: yes
    driver: macvlan
    ipam_config:
      - subnet: "172.24.10.0/24"
        iprange: "172.24.10.128/28"
        gateway: "172.24.10.1"
      - subnet: "2001:44b8:2155:2c10::/64"
        iprange: "2001:44b8:2155:2c10::1000/116"
        gateway: "2001:44b8:2155:2c10::1"
    driver_options:
      parent: "eno1.1"
      macvlan_mode: "bridge"
  tags:
    - docker

- name: Create vlan11 (servers)
  become: true
  docker_network:
    name: dk_v11_srvs
    enable_ipv6: yes
    driver: macvlan
    ipam_config:
      - subnet: "172.24.11.0/24"
        iprange: "172.24.11.128/28"
        gateway: "172.24.11.1"
      - subnet: "2001:44b8:2155:2c11::/64"
        iprange: "2001:44b8:2155:2c11::1000/116"
        gateway: "2001:44b8:2155:2c11::1"
    driver_options:
      parent: "eno1.11"
      macvlan_mode: "bridge"
  tags:
    - docker

- name: Create vlan16 (dns + nat64)
  become: true
  docker_network:
    name: dk_v16_dns
    enable_ipv6: yes
    driver: macvlan
    ipam_config:
      - subnet: "172.24.16.0/24"
        iprange: "172.24.16.128/28"
        gateway: "172.24.16.1"
      - subnet: "2001:44b8:2155:2c16::/64"
        iprange: "2001:44b8:2155:2c16::1000/116"
        gateway: "2001:44b8:2155:2c16::1"
    driver_options:
      parent: "eno1.16"
      macvlan_mode: "bridge"
  tags:
    - docker

- name: Create vlan18 (internet of shit)
  become: true
  docker_network:
    name: dk_v18_ios
    enable_ipv6: yes
    driver: macvlan
    ipam_config:
      - subnet: "172.24.18.0/24"
        iprange: "172.24.18.128/28"
        gateway: "172.24.18.1"
      - subnet: "2001:44b8:2155:2c18::/64"
        iprange: "2001:44b8:2155:2c18::1000/116"
        gateway: "2001:44b8:2155:2c18::1"
    driver_options:
      parent: "eno1.18"
      macvlan_mode: "bridge"
  tags:
    - docker

- name: Create zm volumes
  become: true
  docker_volume:
    name: '{{ item }}'
  with_items:
    - zm_data
    - zm_db
    - zm_logs
  tags:
    - docker
    - zm

- name: Create zm container
  become: true
  docker_container:
    name: zm
    image: zoneminderhq/zoneminder:latest-el7
    restart_policy: unless-stopped
    # pull: yes
    memory: 2048M
    cpu_period: 100000
    # Use 2x cpu
    cpu_quota: 400000
    # device_read_bps:
    # device_read_iops:
    # device_write_bps:
    #   - path: 20M
    # device_write_iops:
    purge_networks: yes
    log_driver: journald
    networks:
      - name: dk_v10_mgmt
        ipv4_address: 172.24.10.129
        ipv6_address: 2001:44b8:2155:2c10::1001
    shm_size: 1024M
    volumes:
      - "zm_data:/var/lib/zoneminder/events"
      - "zm_db:/var/lib/mysql"
      - "zm_logs:/var/log/zm"
    env:
      TZ: "Australia/Brisbane"
  tags:
    - docker
    - zm

- name: Create tayga container
  become: true
  docker_container:
    name: tayga
    image: danehans/tayga:latest
    restart_policy: unless-stopped
    pull: yes
    privileged: yes
    memory: 1024M
    cpu_period: 100000
    cpu_quota: 100000
    purge_networks: yes
    log_driver: journald
    networks:
      - name: dk_v16_dns
        ipv4_address: 172.24.16.129
        ipv6_address: 2001:44b8:2155:2c16::1001
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    env:
      TAYGA_CONF_DATA_DIR: /var/db/tayga
      TAYGA_CONF_DIR: /usr/local/etc
      TAYGA_CONF_IPV4_ADDR: 172.24.16.129
      TAYGA_IPV6_ADDR: 2001:44b8:2155:2c16::1001
      TAYGA_CONF_PREFIX: 2001:44b8:2155:2c64::/96
      TAYGA_CONF_DYNAMIC_POOL: 172.24.64.0/24
  tags:
    - docker
    - tayga

- name: Create micd data volume
  become: true
  docker_volume:
    name: micd_data
  tags:
    - docker
    - micd

- name: Create micd controller
  become: true
  docker_container:
    name: micd
    image: firstyear/micd:latest
    restart_policy: unless-stopped
    pull: yes
    user: 1006:1006
    memory: 400M
    cpu_period: 100000
    cpu_quota: 100000
    purge_networks: yes
    log_driver: journald
    networks:
      - name: dk_v18_ios
        ipv4_address: 172.24.18.140
        ipv6_address: 2001:44b8:2155:2c18::1001
      - name: dk_v10_mgmt
        ipv4_address: 172.24.10.130
        ipv6_address: 2001:44b8:2155:2c10::1002
    volumes:
      - "micd_data:/data"
    env:
      RUST_LOG: "actix=info,micd=info,mic=info"
  tags:
    - docker
    - micd

- name: Create lifx controller
  become: true
  docker_container:
    name: lifx
    image: firstyear/lifx:latest
    restart_policy: unless-stopped
    pull: yes
    user: 1005:1005
    memory: 400M
    cpu_period: 100000
    cpu_quota: 100000
    purge_networks: yes
    log_driver: journald
    networks:
      - name: dk_v18_ios
        ipv4_address: 172.24.18.141
        ipv6_address: 2001:44b8:2155:2c18::1002
      - name: dk_v10_mgmt
        ipv4_address: 172.24.10.131
        ipv6_address: 2001:44b8:2155:2c10::1003
    env:
      RUST_LOG: "actix=debug,lifx=info"
  tags:
    - docker
    - lifx



- name: Create dns64 data volume
  become: true
  docker_volume:
    name: dns64_data
  tags:
    - docker
    - dns64

- name: dns64 config folder
  become: true
  file:
    path: /etc/dns64
    state: directory
    mode: '0750'
  tags:
    - docker
    - dns64

- name: dns64 config
  become: true
  template: src=dns64/named.conf dest=/etc/dns64/named.conf owner=root group=root mode=0644
  with_items:
    - named.conf
  tags:
    - docker
    - dns64

- name: dns64 config
  become: true
  template: src=../../do_not_commit_templates/dns64/{{ item }} dest=/etc/dns64/{{ item }} owner=root group=root mode=0644
  with_items:
    - rndc.key
    - rndc.conf
  tags:
    - docker
    - dns64

- name: Create DNS64 server
  become: true
  docker_container:
    name: dns64
    image: firstyear/dns64:latest
    restart_policy: unless-stopped
    pull: yes
    # user: 1007:1007
    memory: 512M
    cpu_period: 100000
    cpu_quota: 200000
    purge_networks: yes
    log_driver: journald
    networks:
      - name: dk_v16_dns
        ipv4_address: 172.24.16.130
        ipv6_address: 2001:44b8:2155:2c16::1002
    volumes:
      - "dns64_data:/var/lib/named/slave/"
      - "/etc/dns64/named.conf:/etc/named.conf"
      - "/etc/dns64/rndc.key:/etc/rndc.key"
      - "/etc/dns64/rndc.conf:/etc/rndc.conf"
    sysctls:
      net.ipv6.conf.all.accept_ra: 0
      net.ipv6.conf.default.accept_ra: 0
      net.ipv6.conf.eth0.accept_ra: 0
      net.ipv6.conf.all.use_tempaddr: 0
      net.ipv6.conf.default.use_tempaddr: 0
      net.ipv6.conf.ent0.use_tempaddr: 0
  tags:
    - docker
    - dns64

# Bne1 132, 1004

- name: Create kanidm radiusd volume (bne1)
  become: true
  docker_volume:
    name: kanidm_radiusd_bne1
  tags:
    - docker
    - radius
    - kanidm

- name: Configure kanidm radiusd (bne1)
  become: true
  template:
    src: "../../do_not_commit_templates/radiusd_bne1/{{ item }}"
    dest: "/var/lib/docker/volumes/kanidm_radiusd_bne1/_data/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - ca.pem
    - cert.pem
    - config.ini
    - dh
    - kanidm_ca.pem
    - key.pem
  tags:
    - docker
    - radius
    - kanidm

- name: Create kanidm radiusd controller (bne1)
  become: true
  docker_container:
    name: radiusd_bne1
    image: kanidm/radius:latest
    restart_policy: unless-stopped
    pull: yes
    # user: 1008:1008
    memory: 2048M
    cpu_period: 100000
    cpu_quota: 200000
    purge_networks: yes
    log_driver: journald
    networks:
      - name: dk_v10_mgmt
        ipv4_address: 172.24.10.132
        ipv6_address: 2001:44b8:2155:2c10::1004
    volumes:
      - "kanidm_radiusd_bne1:/data"
      - "/etc/resolv.conf:/etc/resolv.conf"
    env:
      DEBUG: "true"
  tags:
    - docker
    - kanidm
    - radius

- name: Create kanidm radiusd volume (bne2)
  become: true
  docker_volume:
    name: kanidm_radiusd_bne2
  tags:
    - docker
    - radius
    - kanidm

- name: Configure kanidm radiusd (bne2)
  become: true
  template:
    src: "../../do_not_commit_templates/radiusd_bne2/{{ item }}"
    dest: "/var/lib/docker/volumes/kanidm_radiusd_bne2/_data/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - ca.pem
    - cert.pem
    - config.ini
    - dh
    - kanidm_ca.pem
    - key.pem
  tags:
    - docker
    - radius
    - kanidm

- name: Create kanidm radiusd controller (bne2)
  become: true
  docker_container:
    name: radiusd_bne2
    image: kanidm/radius:latest
    restart_policy: unless-stopped
    pull: yes
    # user: 1008:1008
    memory: 2048M
    cpu_period: 100000
    cpu_quota: 200000
    purge_networks: yes
    log_driver: journald
    networks:
      - name: dk_v10_mgmt
        ipv4_address: 172.24.10.133
        ipv6_address: 2001:44b8:2155:2c10::1005
    volumes:
      - "kanidm_radiusd_bne2:/data"
      - "/etc/resolv.conf:/etc/resolv.conf"
    env:
      DEBUG: "true"
  tags:
    - docker
    - kanidm
    - radius


### Kanidm

- name: Create docker volume for kanidmd
  become: true
  docker_volume:
    name: kanidmd
  tags:
    - docker
    - kanidm

- name: Create private kanidm network
  become: true
  docker_network:
    name: kanidm_net
    ipam_config:
      - gateway: 172.16.2.1
        iprange: 172.16.2.64/26
        subnet: 172.16.2.0/24
  tags:
    - docker
    - kanidm

- name: Deploy kanidm server.toml
  become: yes
  template: src=base/kanidm/server.toml dest=/var/lib/docker/volumes/kanidmd/_data/server.toml owner=root group=root mode=0644
  tags:
    - docker
    - kanidm

- name: Create kanidmd
  become: true
  docker_container:
    name: kanidmd
    image: kanidm/server:devel
    restart_policy: unless-stopped
    pull: yes
    user: 1400:1400
    memory: 4096M
    cpu_period: 100000
    cpu_quota: 400000
    purge_networks: yes
    log_driver: journald
    networks:
      - name: kanidm_net
        ipv4_address: 172.16.2.120
    volumes:
      - "kanidmd:/data"
    env:
      RUST_BACKTRACE: full
  tags:
    - docker
    - kanidm

- name: Create docker volume for haproxy_certs_le
  become: true
  docker_volume:
    name: kanidm_haproxy_certs_le
  tags:
    - docker
    - haproxy
    - kanidm

- name: Create docker volume for haproxy_certs_cb
  become: true
  docker_volume:
    name: kanidm_haproxy_certs_cb
  tags:
    - docker
    - haproxy
    - kanidm

- name: Create kanidm-haproxy
  become: true
  docker_container:
    name: kanidm-haproxy
    image: firstyear/haproxy-linode-dns:latest
    restart_policy: unless-stopped
    pull: yes
    memory: 1024M
    cpu_period: 100000
    cpu_quota: 100000
    purge_networks: yes
    log_driver: journald
    networks:
      - name: kanidm_net
      - name: dk_v11_srvs
        ipv4_address: 172.24.11.129
        ipv6_address: 2001:44b8:2155:2c11::1001
    volumes:
      - "kanidm_haproxy_certs_le:/etc/letsencrypt"
      - "kanidm_haproxy_certs_cb:/etc/certbot"
    env:
      HAPROXY_TARGET: kanidmd
      HAPROXY_TARGET_PORT: "8080"
      HAPROXY_HOSTNAME: idm.blackhats.net.au
      HAPROXY_LINODE_KEY: "{{ haproxy_linode_key }}"
      HAPROXY_RAW_TARGET_PORT: "3389"
      HAPROXY_RAW_LISTEN_PORT: "636"
  tags:
    - docker
    - haproxy
    - kanidm
  # ports:
  #   - "8000:80"
  #   - "8443:443"
  #   - "8081:8080"
  #   - "636:636"


## UNIFI
# check: python -m json.tool config.gateway.json
# show: mca-ctrl -t dump-cfg
# sudo /opt/vyatta/sbin/dhcpv6-pd-client.pl --ifname pppoe0 --renew
# 
# can ssh to aps with ubnt:ubnt and run;
# mca-cli
# set-inform http://<host_ip>:8080/inform
# set-inform http://172.24.10.134:8080/inform
#

- name: Create unifi data volume
  become: true
  docker_volume:
    name: unifi_data
  tags:
    - docker
    - unifi

- name: Deploy sites config.gateway.json
  become: yes
  template: src=unifi/{{ item }} dest=/var/lib/docker/volumes/unifi_data/_data/{{ item }} owner=root group=root mode=0600
  with_items:
    - sites/default/config.gateway.json
    - sites/abvd2n5d/config.gateway.json
  tags:
    - docker
    - unifi
    - unificfg

- name: Create unifi log volume
  become: true
  docker_volume:
    name: unifi_log
  tags:
    - docker
    - unifi

- name: Create unifi controller
  become: true
  docker_container:
    name: unifi
    image: jacobalberty/unifi:stable
    restart_policy: unless-stopped
    pull: yes
    memory: 2048M
    cpu_period: 100000
    cpu_quota: 200000
    purge_networks: yes
    log_driver: journald
    networks:
      - name: dk_v10_mgmt
        ipv4_address: 172.24.10.134
        ipv6_address: 2001:44b8:2155:2c10::1006
    volumes:
      - "unifi_data:/unifi/data"
      - "unifi_log:/unifi/log"
      - "/etc/localtime:/etc/localtime:ro"
    # env:
    #   TZ: "Australia/Brisbane"
  tags:
    - docker
    - unifi


