
# Deploy loader.conf to /boot/loader.conf
- name: Configure serial console
  become: yes
  template: src=loader.conf dest=/boot/loader.conf owner=root group=wheel mode=0644

# Install packages
#  sudo zsh sssd python? openldap-clients?
#  which load balancer? haproxy?
#  bgpd?
#  openvpn? openconnect?

- name: Install packages
  become: yes
  ignore_errors: yes
  pkgng: name={{ item }} state=present
  with_items:
    - dhcp6
    - isc-dhcp43-server
    - sssd
    - sudo
    - python36
    - openldap-client
    - zsh
    - vim-lite
    - haproxy
    - openbgpd
    - openvpn
    # - openvpn-auth-ldap

# Deploy auth configs

- name: symlink zsh to correct location
  become: yes
  file: src=/usr/local/bin/zsh dest=/bin/zsh state=link

- name: Configure secure configurations
  become: yes
  template: src=../../templates/auth/{{ item }} dest=/usr/local/etc/{{ item }} owner=root group=wheel mode=0600
  with_items:
    - sssd/sssd.conf
    - sudoers.d/bh_admins-sudo

- name: configurations AUTH (/usr/local/etc)
  become: yes
  template: src=../../templates/auth/{{ item }} dest=/usr/local/etc/{{ item }} owner=root group=wheel mode=0644
  with_items:
    - openldap/ldap.conf

- name: Create tls cert dir
  become: yes
  file: path=/etc/pki/tls/certs state=directory mode=0755 owner=root group=wheel

- name: Configure AUTH configurations (/etc)
  become: yes
  template: src=../../templates/auth/{{ item }} dest=/etc/{{ item }} owner=root group=wheel mode=0644
  with_items:
    - pki/tls/certs/bh_ldap.crt
    - pam.d/system
    - pam.d/sshd
    - ssh/sshd_config

- name: configurations (/usr/local/etc)
  become: yes
  template: src={{ item }} dest=/usr/local/etc/{{ item }} owner=root group=wheel mode=0644
  with_items:
    - dhcpd.conf
    - dhcp6c.conf

- name: configurations (/etc)
  become: yes
  template: src={{ item }} dest=/etc/{{ item }} owner=root group=wheel mode=0644
  with_items:
    - rtadvd.conf
    - ppp/ppp.linkup

# Configure pf.conf
- name: Configure pf
  become: yes
  template: src=pf.conf dest=/etc/pf.conf owner=root group=wheel mode=0644

- name: Enable pf
  become: yes
  lineinfile: path=/etc/rc.conf line='pf_enable="YES"'

- name: Enable pflog
  become: yes
  lineinfile: path=/etc/rc.conf line='pflog_enable="YES"'

- name: Enable sysctls for routing ipv4
  become: yes
  lineinfile: path=/etc/rc.conf line='gateway_enable="YES"'

- name: Enable sysctls for routing ipv6
  become: yes
  lineinfile: path=/etc/rc.conf line='ipv6_gateway_enable="YES"'

- name: Validate firewall
  become: true
  command: /sbin/pfctl -nf /etc/pf.conf

- name: Apply firewall
  become: true
  command: /sbin/pfctl -f /etc/pf.conf

- name: PPP enable
  become: yes
  blockinfile:
    path: /etc/rc.conf
    block: |
      ppp_enable="YES"
      ppp_program="/usr/sbin/ppp"
      ppp_nat="YES"
      ppp_user="root"
      ppp_profile="internode"
      ppp_internode_mode="ddial"
      ppp_internode_nat="YES"

### VPN end point configurations

- name: create openvpn dir
  become: yes
  file: path=/usr/local/etc/openvpn owner=root group=wheel mode=0755 state=directory

- name: template openvpn configs
  become: yes
  template: src=openvpn/{{ item }} dest=/usr/local/etc/openvpn/{{ item }} owner=root group=wheel mode=0644
  with_items:
    - openvpn_vps.conf
    - openvpn_mic.conf
    - openvpn_kee.conf
    - ccd/fnog.concrete.lan
    - ccd/bb22.lab.baudbit.net

- name: template openvpn scripts
  become: yes
  template: src=openvpn/{{ item }} dest=/usr/local/etc/openvpn/{{ item }} owner=root group=wheel mode=0750
  with_items:
    - up_kee.sh
    - up_mic.sh

- name: link rc.d scripts
  become: yes
  file: src=/usr/local/etc/rc.d/openvpn dest=/usr/local/etc/rc.d/openvpn_{{ item }} owner=root group=wheel mode=0644 state=link
  with_items:
    - vps
    - mic
    - kee

# deploy network interface configs
# set rc.conf

# bgpd config
# /usr/local/etc/bgpd.conf 0600

# Do we do this all with "ensure line"?

- name: Enable SSSD
  become: yes
  lineinfile: path=/etc/rc.conf line='sssd_enable="YES"'

- name: Enable dhcpd
  become: yes
  lineinfile: path=/etc/rc.conf line='dhcpd_enable="YES"'

- name: Enable dhcp6c
  become: yes
  lineinfile: path=/etc/rc.conf line='dhcp6c_enable="YES"'

- name: Enable dhcp6c interfaces
  become: yes
  lineinfile: path=/etc/rc.conf line='dhcp6c_interfaces="tun0"'

- name: Enable rtadvd
  become: yes
  lineinfile: path=/etc/rc.conf line='rtadvd_enable="YES"'

- name: Enable vps openvpn end point
  become: yes
  lineinfile: path=/etc/rc.conf line='openvpn_vps_enable="YES"'

# pf_enable="YES" ???


