
# We need to create a symlink for python, else ansible won't work.
# This is just here as documentation and assertion.

- name: Symlink python
  file: src=/usr/local/bin/python2.7 dest=/usr/bin/python state=link
  become: true

- name: Install packages
  become: true
  openbsd_pkg: name={{ item }} state=present
  with_items:
    - sudo
    - python
    - vim
    - isc-dhcp-server
    - wide-dhcpv6
    - openvpn
    # - openvpn-auth-ldap
    - zsh
    - nmap
    # - gcc-libs # This resolves a problem with openbsd 6 and openvpn ldap
    # - curl
    # - glib2
    # - gtar
    # - gnupg
    # - gmake
    - ocserv
    - vnstat

# First, we bootstrap the router with BGP. This is used post install for connection
# to nextyear, but initially it allows us a default route via vio7.

- name: Configure Base System
  become: true
  template: src={{ item }} dest=/etc/{{ item }} owner=root group=wheel mode=0644
  with_items:
    - resolv.conf
    - rc.conf.local
    - dhcpd.conf
    - rtadvd0.conf
    - inetd.conf
    - sysctl.conf
    - dhcp6c.conf
    - relayd.conf
    # - amanda-security.conf
    - ssh/sshd_config
    - radcli/radiusclient.conf

- name: Configure secure base system
  become: true
  template: src={{ item }} dest=/etc/{{ item }} owner=root group=wheel mode=0600
  with_items:
    - radcli/servers

- name: Deploy init scripts
  become: true
  template: src=rc.d/{{ item }} dest=/etc/rc.d/{{ item }} owner=root group=wheel mode=0755
  with_items:
    - rtadvd0

- name: Configure Routing
  become: true
  template: src={{ item }} dest=/etc/{{ item }} owner=root group=wheel mode=0640
  with_items:
    - bgpd.conf
    - ospfd.conf

- name: Configure network interfaces
  become: true
  template: src={{ item }} dest=/etc/{{ item }} owner=root group=wheel mode=0640
  with_items:
    - hostname.vio0
    - hostname.vio1
    - hostname.vio2
    - hostname.vio3
    - hostname.vio4
    - hostname.vio5
    - hostname.vio6
    - hostname.vio7
    - hostname.vio8
    - hostname.tun0
    - hostname.tun2
    - hostname.tun3

- name: Config openvpn client dirs
  become: true
  file: path=/etc/openvpn/syd1-clients/ owner=root group=wheel mode=0755 state=directory

- name: Configure openvpn
  become: true
  template: src=openvpn/{{ item }} dest=/etc/openvpn/{{ item }} owner=_openvpn group=wheel mode=0640
  with_items:
    # - auth-ldap.conf
    # - roaming.conf
    - vpn-bne1-adl1.conf
    - vpn-bne1-syd1.conf
    - syd1-clients/vpn-syd1.net.blackhats.net.au

- name: Configure openvpn scripts
  become: true
  template: src=openvpn/{{ item }} dest=/etc/openvpn/{{ item }} owner=_openvpn group=wheel mode=0755
  with_items:
    - vpn-syd1.sh

- name: Configure firewall
  become: true
  template: src=pf.conf dest=/etc/pf.conf owner=root group=wheel mode=0600

- name: Validate firewall
  become: true
  command: /sbin/pfctl -nf /etc/pf.conf

- name: Reload firewall
  become: true
  command: /sbin/pfctl -f /etc/pf.conf

# - name: Amanda configuration
#   become: true
#   template: src=amanda/{{ item }} dest=/var/lib/amanda/{{ item }} owner=amanda group=backup mode=0644
#   with_items:
#     - exclude
#     - backup-pubkey.pem
# 
# - name: Amanda secure configuration
#   become: true
#   template: src=amanda/{{ item }} dest=/var/lib/amanda/{{ item }} owner=amanda group=backup mode=0600
#   with_items:
#     - exclude
#     - backup-pubkey.pem
#     - .amandahosts
# 
# - name: Amanda tarlists
#   become: true
#   file: path=/usr/local/amanda/var/amanda/gnutar-lists owner=amanda group=backup mode=0755 state=directory

# To build amanda client:
#
# curl -o amanda-3.3.9.tar.gz http://downloads.sourceforge.net/project/amanda/amanda%20-%20stable/3.3.9/amanda-3.3.9.tar.gz
# gtar -xvf amanda-3.3.9.tar.gz
# cd amanda-3.3.9
# sudo groupadd backup
# sudo useradd -g backup -m -d /var/lib/amanda amanda
# ./configure --prefix=/usr/local/amanda --with-gnutar=/usr/local/bin/gtar --without-server --with-client
# gmake
# sudo gmake install
# sudo cp common-src/amcrypt-ossl-asym /sbin/
# chmod 755 /sbin/amcrypt-ossl-asym
#
# to /etc/services append
# amanda 10080/tcp #amanda backup services
# amanda 10080/udp #amanda backup services
#



# /etc/radcli/radiusclient.conf
# /etc/radcli/servers
# /etc/ocserv/ocserv

- name: Configure ocserv
  become: true
  template: src={{ item }} dest=/etc/{{ item }} owner=root group=_ocserv mode=0644
  with_items:
    - ocserv/ocserv.conf

