
- name: reload firewalld
  shell: /usr/bin/firewall-cmd --reload

- name: resize xfs
  sudo: yes
  shell: /usr/sbin/xfs_growfs /dev/vg00/var_lv

- name: remount xfs
  sudo: yes
  shell: /usr/bin/mount -o remount /dev/vg00/var_lv

