


- name: Install mediawiki and postgres
  sudo: yes
  action: yum name={{ item }} state=present
  with_items:
    - httpd
    - postgresql
    - postgresql-server
    - mediawiki123
    - php-pgsql
    - mod_ssl
    - certbot

- name: Deploy mediawiki config
  sudo: yes
  action: template src={{ item }} dest=/etc/httpd/conf.d/{{ item }} owner=root group=root mode=0644
  with_items:
    - ssl.conf
    - mediawiki.conf

- name: Enable postgresql
  sudo: yes
  action: service name=postgresql state=started enabled=yes

- name: Enable httpd
  sudo: yes
  action: service name=httpd state=started enabled=yes

- name: Enable pgsql dump
  sudo: yes
  action: cron name="Backup PGSQL" minute="15" hour="1" job="/usr/bin/pg_dump bs_wiki_prd > /var/lib/pgsql/backups/bs_wiki_prd.sql" user="postgres"

- name: config http firewalld
  sudo: yes
  firewalld: service={{ item }} zone=internal permanent=yes state=enabled immediate=yes
  with_items:
    - http
    - https

- name: cron the lets encrypt renewal
  sudo: yes
  action: cron name="Renew le cert blog" minute="43" hour="8" job="/usr/bin/certbot renew" user="root"

