# Is there a way to make sure that the template exists? 
- include_vars: postinst.yml

- name: Ensure VM exists
  local_action: ovirt
    state=present
    instance_name={{ inventory_hostname }}
    user={{ ovirt_admin_username }}
    password="{{ ovirt_admin_password }}"
    url={{ ovirt_engine }}
    region={{ ovirt_dc }}
    zone={{ ovirt_cluster }}
    sdomain={{ ovirt_sdomain }}
    resource_type=template
    instance_type=server
    instance_cpus={{ ovirt_instance_cpus }}
    instance_mem={{ ovirt_instance_mem }}
    image=centos.{{ centos_version }}.{{ ipa_domain }}
    timeout=1800
    wait_for_state=down

#notify:
#  - configure cloud init

- meta: flush_handlers

- name: ovirt launch instance
  local_action: ovirt
    state=started
    instance_name={{ inventory_hostname }}
    user={{ ovirt_admin_username }}
    password="{{ ovirt_admin_password }}"
    url={{ ovirt_engine }}
    wait_for_state=up
    timeout=120

