
- name: Ensure postfix
  sudo: yes
  action: yum name=postfix state=present

- name: Ensure dovecot
  sudo: yes
  action: yum name=dovecot state=present

- name: Ensure dovecot sieve
  sudo: yes
  action: yum name=dovecot-pigeonhole state=present

- name: Ensure clamav-milter
  sudo: yes
  action: yum name=clamav-milter state=present

- name: Ensure spamass-milter-postfix
  sudo: yes
  action: yum name=spamass-milter-postfix state=present

- name: Ensure spamass-milter
  sudo: yes
  action: yum name=spamass-milter state=present

- name: Ensure clamav-milter-systemd
  sudo: yes
  action: yum name=clamav-milter-systemd state=present

- name: Ensure clamav-server
  sudo: yes
  action: yum name=clamav-server state=present

- name: Ensure spamassassin
  sudo: yes
  action: yum name=spamassassin state=present

### Now actually do some configuration.



