
- name: Install mail software
  sudo: yes
  action: yum name={{ item }} state=present
  with_items:
   - postfix
   - dovecot
   - dovecot-pigeonhole
   - clamav-milter
   - spamass-milter
   - clamav-milter-systemd
   - clamav-server-systemd
   - spamassassin

- name: Create smtpd link
  sudo: yes
  action: file src=/usr/lib/systemd/system/clamd@.service dest=/etc/systemd/system/clamd@clamsmtp.service state=link

- name: config email firewalld
  sudo: yes
  firewalld: service={{ item }} zone=internal permanent=yes state=enabled immediate=yes
  with_items:
    - smtp
    - imaps

- name: config email ports firewalld
  sudo: yes
  firewalld: port={{ item }} zone=internal permanent=yes state=enabled immediate=yes
  with_items:
    - 143/tcp
    - 465/tcp

### Now actually do some configuration.

# Config the email storage. Make sure the lvol is big enough.
- name: Resize /var for content
  sudo: yes
  lvol: vg=vg00 lv=var_lv size=10g
  notify:
    - resize xfs
    - remount xfs

# Config the email storage. Make sure the lvol is big enough.
- name: Resize /var/log for logs
  sudo: yes
  lvol: vg=vg00 lv=var_log_lv size=6g
  notify:
    - resize xfs
    - remount xfs

# Create SSL keys? How do we best manage this with IPA?


# Deploy all the configs. Which ones have we changed? Maybe I need a default install
#  to diff against.

- name: Deploy dovecot configurations
  sudo: yes
  template: src=etc/dovecot/{{ item }} dest=/etc/dovecot/{{ item }} owner=root group=root mode=0644
  with_items:
    - conf.d/10-auth.conf
    - conf.d/10-mail.conf
    - conf.d/10-master.conf
    - conf.d/15-lda.conf
    - conf.d/20-imap.conf
    - conf.d/90-quota.conf
    - conf.d/auth-ldap.conf.ext
    - conf.d/90-sieve.conf
    - conf.d/10-ssl.conf
    - dovecot.conf
    - dovecot-ldap.conf.ext
  notify: restart dovecot

- name: Deploy postfix configurations
  sudo: yes
  template: src=etc/postfix/{{ item }} dest=/etc/postfix/{{ item }} owner=root group=root mode=0644
  with_items:
    - main.cf
    - master.cf
    - virtual_domains
  notify: restart postfix

## When some things like transport are deployed, rehash them

- name: Deploy clam milter config
  sudo: yes
  template: src=etc/mail/clamav-milter.conf dest=/etc/mail/clamav-milter.conf owner=root group=root mode=0644
  notify: restart clamav-milter

- name: Deploy clam config
  sudo: yes
  template: src=etc/clamd.d/clamsmtp.conf dest=/etc/clamd.d/clamsmtp.conf owner=root group=root mode=0644
  notify: restart clamd

# Need a notify to restart bits ...

## Still need to add clamav and spamassasin bits.

- name: Enable mail services
  sudo: yes
  service: name={{ item }} state=started enabled=yes
  with_items:
    - spamass-milter
    - clamd@clamsmtp
    - clamav-milter
    - postfix
    - dovecot

