
- name: Install mail software
  sudo: yes
  action: yum name={{ item }} state=present
  with_items:
   - postfix
   - dovecot
   - dovecot-pigeonhole
   - clamav-milter
   - spamass-milter
   - clamav-milter-systemd
   - spamassassin

### Now actually do some configuration.



