
# Should we ensure that we have a git repo?

- name: Build 389ds
  shell: chdir="{{ ds_path }}" executable=/bin/zsh make

- name: Install 389ds
  sudo: yes
  shell: chdir="{{ ds_path }}" executable=/bin/zsh make install
