
- name: Install bind and vpn
  become: true
  action: yum name={{ item }} state=present
  with_items:
    - bind
    - openvpn

# Deploy the configs here
- name: deploy openvpn config
  become: true
  action: template src=dns-slave/openvpn-client-bne1.conf dest=/etc/openvpn/client/bne1.conf owner=root group=named mode=0640

- name: deploy named configs
  become: true
  action: template src=dns-slave/{{ item }} dest=/etc/{{ item }} owner=root group=named mode=0640
  with_items:
    - named.conf
  notify: restart named

- name: Enable dns services
  become: true
  action: service name={{ item }} state=started enabled=yes
  with_items:
    - named
    - openvpn-client@bne1

- name: config dns firewall
  become: true
  action: firewalld service=dns zone=internal permanent=yes state=enabled immediate=yes
