
# certbot --test-cert certonly -m william@blackhats.net.au --manual --preferred-challenges=dns --manual-public-ip-logging-ok --agree-tos -d test-cert.net.blackhats.net.au
# After the DNS challenge is done, then all good to go

- name: Fix SUSE admin groups
  become: yes
  user: name=admin groups=wheel append=yes

- name: Detect if we are transactional SUSE install
  become: yes
  stat: path=/usr/sbin/transactional-update
  register: trans_suse

- name: sysctl for atomic hosts
  template: src=base/sysctl/{{ item }} dest=/etc/sysctl.d/{{ item }} owner=root group=root mode=0644
  become: yes
  with_items:
    - 01-uofa.conf

- name: Configure SUSE packages
  become: yes
  ignore_errors: yes
  zypper:
    name: ['sssd', 'sssd-ad', 'sssd-ldap', 'sssd-tools', 'docker', 'zsh', 'python3-pyOpenSSL', 'certbot', 'ipcalc', 'python3-docker', 'mozilla-nss-tools', 'rdiff-backup', 'avahi']
    state: present
  when: "ansible_os_family == 'Suse' and trans_suse.stat.exists == False"

# Also:
# zypper ar obs://home:firstyear:kanidm home:firstyear:kanidm
# zypper ref
# transactional-update pkg install kanidm-clients


- name: Configure Kanidm configuration
  become: yes
  template: src=base/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - kanidm/config
    - kanidm/sshd_config
  tags:
    - kanidm_client

- name: Configure secure LDAP configurations
  become: yes
  template: src=../../templates/auth/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0600
  with_items:
    - sssd/sssd.conf
    - sudoers.d/bh_admins-sudo

# - name: Touch preauth avail
#   become: yes
#   file: state=touch mode=0644 path=/var/lib/sss/pubconf/pam_preauth_available

- name: Ensure tls/certs directory
  become: yes
  file: state=directory mode=0755 path=/etc/pki/tls/certs owner=root group=root

- name: Configure hostname
  become: yes
  template: src=../../templates/auth/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - hostname
  when: "inventory_hostname != 'localhost'"

- name: Push SSCA script to all hosts
  become: yes
  template: src=../../scripts/ssca.py dest=/root/ssca.py owner=root group=root mode=0755

- name: Push systemd unit files
  become: yes
  template: src=base/systemd/{{ item }} dest=/etc/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - certbot.service
    - certbot.timer
  notify: daemon-reload
  when: "ansible_os_family != 'Suse'"

- meta: flush_handlers

- name: Ensure services disabled
  become: yes
  ignore_errors: yes
  service: name={{ item }} enabled=no
  with_items:
    - nfs-client.target
    - certmonger
    - ntpd
    - nscd

# - name: Deploy docker daemon configuration
#   become: yes
#   ignore_errors: yes
#   template: src=base/docker/daemon.json dest=/etc//docker/daemon.json owner=root group=root mode=0644

- name: Ensure services enabled
  become: yes
  ignore_errors: yes
  service: name={{ item }} enabled=yes
  with_items:
    - sssd
    - sshd
    - docker
    - chronyd
    - certbot.timer

# How to handle this for suse transactional os?
# systemctl enable --now transactional-update.timer
# systemctl enable --now rebootmgr.service

- name: Ensure transactional services enabled
  become: yes
  ignore_errors: yes
  service: name={{ item }} enabled=yes
  with_items:
    - rebootmgr.service
    - transactional-update.timer
  when: "ansible_os_family == 'Suse' and trans_suse.stat.exists == True"

- name: Configure Fedora AUTH configurations
  become: yes
  template: src=../../templates/auth/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - pki/tls/certs/bh_ldap.crt
    - pam.d/password-auth-ac
    - pam.d/system-auth-ac
    - ssh/sshd_config
    - openldap/ldap.conf
  when: "ansible_os_family != 'Suse'"

- name: Configure SUSE AUTH configurations
  become: yes
  template: src=../../templates/auth/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    # Need to mkdir this?
    - pam.d/common-account-pc
    - pam.d/common-auth-pc
    - pam.d/common-password-pc
    - pam.d/common-session-pc
    # - ssh/sshd_config
    - openldap/ldap.conf
    - nsswitch.conf
    - nscd.conf
    - pki/tls/certs/bh_ldap.crt
  when: "ansible_os_family == 'Suse'"

- name: Fix SUSE sudoers
  become: yes
  template: src=../../templates/auth/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0400
  with_items:
    - sudoers
  when: "ansible_os_family == 'Suse'"

# /usr/libexec/sssd/p11_child --pre --nssdb=/etc/pki/nssdb 
# to check certs.
# Add cert to db?
# You need coolkey installed (I think ...)

# certutil -A -d /etc/pki/nssdb -i /etc/pki/tls/certs/bh_ldap.crt -n BH_LDAP_CA -t "CT,,"

# modutil modutil -dbdir /etc/pki/nssdb -add "My PKCS#11 modules" -libfile libmypkcs11.so
# modutil -dbdir /etc/pki/nssdb -add "coolkey" -libfile /usr/lib64/libcoolkeypk11.so

# semanage permissive -a sssd_t

- name: Server configurations
  include: server.yml
  when: "'workstation' not in group_names and 'htpc' not in group_names"

- name: Suse Workstation
  include: suse-workstation.yml
  when: "ansible_os_family == 'Suse' and 'workstation' in group_names"

# - name: Build Containers
#   include: container-build.yml
#   when: "'workstation' in group_names and 'localhost' in inventory_hostname"

- name: Server Contain Configuration
  include: containers/main.yml
  when: "'workstation' not in group_names and 'htpc' not in group_names"

# - name: DNS Slave Deployment
#   include: dns-slave.yml
#   when: "'dns_slave_servers' in group_names"

- name: Spotinuc
  include: spotinuc.yml
  when: "'htpc' in group_names"

