# For converting to tumbleweed:
# rm /etc/zypp/repos.d/*.repo
# zypper ar -f -c http://download.opensuse.org/tumbleweed/repo/oss repo-oss
# zypper ar -f -c http://download.opensuse.org/tumbleweed/repo/non-oss repo-non-oss
# zypper ar -f -c http://download.opensuse.org/tumbleweed/repo/debug repo-debug
# zypper ar -f -c http://download.opensuse.org/update/tumbleweed/ repo-update
# zypper ar obs://home:firstyear:kanidm home:firstyear:kanidm
# zypper mr -f home_firstyear_kanidm
# zypper ref
#
# in nmcli
# set ipv6.addr-gen-mode  eui64

# certbot --test-cert certonly -m william@blackhats.net.au --manual --preferred-challenges=dns --manual-public-ip-logging-ok --agree-tos -d test-cert.net.blackhats.net.au
# After the DNS challenge is done, then all good to go

- name: Fix SUSE admin groups
  become: yes
  user: name=admin groups=wheel append=yes

- name: Detect if we are transactional SUSE install
  become: yes
  stat: path=/usr/sbin/transactional-update
  register: trans_suse

- name: sysctl for atomic hosts
  template: src=base/sysctl/{{ item }} dest=/etc/sysctl.d/{{ item }} owner=root group=root mode=0644
  become: yes
  with_items:
    - 01-uofa.conf

- name: Configure SUSE packages
  become: yes
  ignore_errors: yes
  zypper:
    name: ['tmux', 'docker', 'zsh', 'ipcalc', 'python3-docker', 'mozilla-nss-tools', 'avahi', 'borgbackup', 'kanidm-clients', 'kanidm-unixd-clients', 'nmap', 'tcpdump']
    state: present
  when: "ansible_os_family == 'Suse' and trans_suse.stat.exists == False"

# transactional-update pkg install kanidm-clients kanidm-unixd-clients

- name: Configure Kanidm configuration
  become: yes
  template: src=base/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - kanidm/config
    - kanidm/unixd
  tags:
    - kanidm_client

- name: Configure kanidm unixd service enabled
  become: yes
  service: name=kanidm-unixd enabled=yes state=started
  tags:
    - kanidm_client

- name: Configure secure kanidm configurations
  become: yes
  template: src=base/kanidm/{{ item }} dest=/etc/sudoers.d/{{ item }} owner=root group=root mode=0600
  with_items:
    - net_admins-sudo
  tags:
    - kanidm_client

- name: Configure Kanidm ssh configuration
  become: yes
  template: src=base/kanidm/{{ item }} dest=/etc/ssh/{{ item }} owner=root group=root mode=0644
  with_items:
    - sshd_config
  tags:
    - kanidm_client
  notify: restart sshd

- meta: flush_handlers

- name: Configure Kanidm unixd configuration
  become: yes
  template: src=base/kanidm/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - pam.d/common-password-pc
    - pam.d/common-session-pc
    - pam.d/common-auth-pc
    - pam.d/common-account-pc
    - nsswitch.conf
  tags:
    - kanidm_client

# This breaks some applications on suse if we ensure it, make sure we DONT have it I guess ...
- name: Ensure tls/certs directory removed
  become: yes
  file: state=absent path=/etc/pki/tls/certs

- name: Configure hostname
  become: yes
  template: src=../../templates/auth/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - hostname
  when: "inventory_hostname != 'localhost'"

- name: Push SSCA script to all hosts
  become: yes
  template: src=../../scripts/ssca.py dest=/root/ssca.py owner=root group=root mode=0755

- name: Ensure services disabled
  become: yes
  ignore_errors: yes
  service: name={{ item }} enabled=no
  with_items:
    - nfs-client.target
    - certmonger
    - ntpd
    - nscd
    - firewalld
    - sssd

- name: Ensure services enabled
  become: yes
  ignore_errors: yes
  service: name={{ item }} enabled=yes
  with_items:
    - sshd
    - docker
    - chronyd
    - certbot.timer
    - avahi-daemon

- name: Ensure transactional services enabled
  become: yes
  ignore_errors: yes
  service: name={{ item }} enabled=yes
  with_items:
    - rebootmgr.service
    - transactional-update.timer
  when: "ansible_os_family == 'Suse' and trans_suse.stat.exists == True"

# When we aren't transactional, we still want auto updates though.
# Note, that mion is transactional, so this won't accidentally capture that.
- name: Push systemd unit files
  become: yes
  template: src=base/systemd/{{ item }} dest=/etc/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - zypperupdate.service
    - zypperupdate.timer
  notify: daemon-reload
  when: "ansible_os_family == 'Suse' and trans_suse.stat.exists != True"

- meta: flush_handlers

- name: Ensure zypper update services enabled
  become: yes
  ignore_errors: yes
  service: name={{ item }} enabled=yes
  with_items:
    - zypperupdate.timer
  when: "ansible_os_family == 'Suse' and trans_suse.stat.exists != True"

- name: Configure SUSE AUTH configurations
  become: yes
  template: src=../../templates/auth/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - nscd.conf
  when: "ansible_os_family == 'Suse'"

- name: Fix SUSE sudoers
  become: yes
  template: src=../../templates/auth/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0400
  with_items:
    - sudoers
  when: "ansible_os_family == 'Suse'"

- name: Server configurations
  include: server.yml
  when: "'htpc' not in group_names"

- name: Server Container Configuration
  include: containers/main.yml
  when: "'htpc' not in group_names"

- name: Spotinuc
  include: spotinuc.yml
  when: "'htpc' in group_names"

- name: Backup Client
  include: borgbackup.yml
  when: "'DailySet1' in group_names"

- name: Mail Router
  include: mailrouter.yml
  when: "'email_relay_servers' in group_names"

- name: Blog Server
  include: blog.yml
  when: "'blog_servers' in group_names"

- name: dns64
  include: dns64.yml
  when: "'dns64' in group_names"


