
# Install: transactional-update pkg install apache2 nagios-www nagios nagios-contrib 
# monitoring-plugins-ldap monitoring-plugins-radius monitoring-plugins-rsync monitoring-plugins-apcupsd

# Ensure you run a2enmod php7

- name: Apache in nagios group for cmd
  become: yes
  user: name=wwwrun group=nagios append=yes
  tags:
    - nagios

- name: Fix effective rights mask
  become: yes
  acl:
    path: /var/spool/nagios
    etype: mask
    permissions: rw
    state: present
    default: yes
  tags:
    - nagios

- name: Allow apache to write to cmd
  become: yes
  acl:
    path: /var/spool/nagios
    etype: user
    entity: wwwrun
    permissions: rw
    state: present
    default: yes
  tags:
    - nagios

- name: Base nagios config
  become: yes
  template: src=nagios/{{ item }} dest=/etc/nagios/{{ item }} owner=root group=root mode=0644
  with_items:
    - nagios.cfg
    - cgi.cfg
  tags:
    - nagios

- name: Deploy nagios site configurations
  become: yes
  template: src=nagios/{{ item }} dest=/etc/nagios/objects/{{ item }} owner=root group=root mode=0644
  with_items:
    - bne1-network.cfg
    - bne1-servers.cfg
    - bne2-network.cfg
    - contacts.cfg
    - ex-commands.cfg
    - templates.cfg
  tags:
    - nagios

- name: Deploy nagios apache2 configuration
  become: yes
  template: src=nagios/vhost-nagios.conf dest=/etc/apache2/vhosts.d/nagios.conf owner=root group=root mode=0644
  tags:
    - nagios

- name: Enable nagios services
  become: yes
  service: name={{ item }} enabled=yes
  with_items:
    - nagios
    - nagios-archive.timer
    - apache2
  tags:
    - nagios


