
# Install kodi,  vlc, firefox etc

- name: Configure SUSE spotinuc packages
  become: yes
  zypper:
    name: ['flatpak', 'vlc']
    state: present

- name: Deploy gdm autologin
  become: yes
  action: template src=spotinuc/custom.conf dest=/etc/gdm/custom.conf owner=root group=root mode=0644

- name: Create autostarts
  become: yes
  action: file src=/usr/share/applications/{{ item }} dest=/home/admin/.config/autostart/{{ item }} state=link owner=admin group=users mode=0755
  with_items:
    #- kodi.desktop
    - firefox.desktop

- name: Make kodi dirs
  become: yes
  action: file path=/home/admin/.kodi/userdata/sources state=directory owner=admin group=users mode=0755

- name: Deploy kodi sources
  become: yes
  action: template src=spotinuc/sources.xml dest=/home/admin/.kodi/userdata/sources.xml owner=admin group=users mode=0644

