- name: zfs kmod configuration
  become: yes
  template: src=zfs/module.conf dest=/etc/modprobe.d/zfs.conf owner=root group=root mode=0644
  tags:
    - zfs

- name: zfs monitoring config
  become: yes
  template: src=nagios/fileserver-nrpe.cfg dest=/etc/nrpe.d/fileserver-nrpe.cfg owner=root group=root mode=0644
  tags:
    - nrpe
    - zfs

- name: zfs unit files
  become: yes
  template: src=zfs/{{ item }} dest=/etc/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - zfs-auto-snapshot-hourly.timer
    - zfs-auto-snapshot-hourly.service
    - zfs-scrub-weekly.timer
    - zfs-scrub-weekly.service
  tags:
    - zfs
    - zfstasks

- name: zfs timers enabled
  become: yes
  service: name={{ item }} enabled=yes state=started
  with_items:
    - zfs-auto-snapshot-hourly.timer
    - zfs-scrub-weekly.timer
  tags:
    - zfs
    - zfstasks

- name: zfs tank settings
  become: yes
  zfs:
    name: tank
    state: present
    extra_zfs_properties:
      mountpoint: /mnt
      relatime: on
      dnodesize: auto
      setuid: off
      exec: off
      devices: off
  tags:
    - zfs

- name: zfs tank/comp settings
  become: yes
  zfs:
    name: tank/comp
    state: present
    extra_zfs_properties:
      mountpoint: /mnt/comp
      compression: on
  tags:
    - zfs

- name: zfs tank/comp/pub
  become: yes
  zfs:
    name: tank/comp/pub
    state: present
    extra_zfs_properties:
      mountpoint: /mnt/comp/pub
      recordsize: 1M
      quota: 4T
  tags:
    - zfs

- name: zfs tank/comp/backups
  become: yes
  zfs:
    name: tank/comp/backups
    state: present
    extra_zfs_properties:
      mountpoint: /mnt/comp/backups
      recordsize: 4K
      quota: 2500G
  tags:
    - zfs

- name: zfs tank/comp/home
  become: yes
  zfs:
    name: tank/comp/home
    state: present
    extra_zfs_properties:
      mountpoint: /mnt/comp/home
      quota: 1500G
      snapdir: visible
  tags:
    - zfs

- name: zfs tank/comp/home/*
  become: yes
  zfs:
    name: "tank/comp/home/{{ item }}"
    state: present
    extra_zfs_properties:
      mountpoint: "/mnt/comp/home/{{ item }}"
  with_items:
    - charcol
    - william
    - scanner
  tags:
    - zfs

- name: zfs tank/comp/home/charcol/important
  become: yes
  zfs:
    name: tank/comp/home/charcol/important
    state: present
    extra_zfs_properties:
      mountpoint: /mnt/comp/home/charcol/important
      copies: 2
  tags:
    - zfs

- name: zfs tank/libvirt settings
  become: yes
  zfs:
    name: tank/libvirt
    state: present
    extra_zfs_properties:
      mountpoint: /mnt/libvirt
      primarycache: metadata
      quota: 1T
  tags:
    - zfs

- name: zfs tank/libvirt/iso settings
  become: yes
  zfs:
    name: tank/libvirt/iso
    state: present
    extra_zfs_properties:
      mountpoint: /mnt/libvirt/iso
      recordsize: 1M
  tags:
    - zfs

- name: zfs tank/libvirt/img settings
  become: yes
  zfs:
    name: tank/libvirt/img
    state: present
    extra_zfs_properties:
      mountpoint: /mnt/libvirt/img
      recordsize: 4K
  tags:
    - zfs

