

- name: Configure amanda service socket
  sudo: yes
  service: name=amanda.socket enabled=yes state=started

- name: Configure Amanda allowed hosts
  sudo: yes
  copy: src=var/lib/amandahosts dest=/var/lib/amanda/.amandahosts owner=root group=root mode=0644


