
- name: Activate firewalld
  sudo: yes
  service: name=firewalld enabled=yes state=started

- name: Configure amanda firewall
  sudo: yes
  firewalld: service=amanda-client zone=internal permanent=yes state=enabled #immediate=yes
  notify:
    - reload firewalld

- name: Remove Samba Internal
  sudo: yes
  firewalld: zone=internal permanent=true state=disabled service=samba-client
  notify:
    - reload firewalld

- name: Remove Samba Internal
  sudo: yes
  firewalld: zone=internal permanent=true state=disabled service=mdns
  notify:
    - reload firewalld

- name: Change default zone
  sudo: yes
  shell: /usr/bin/firewall-cmd --set-default-zone=internal
  notify:
    - reload firewalld

