
# We are relying on this being installed by ks.

- name: Install guest software
  sudo: yes
  yum: name=ovirt-guest-agent-common state=present

- name: Activate agent
  sudo: yes
  service: name=ovirt-guest-agent enabled=yes state=started

