
## Install the packages
- name: Install ipa and radiusd
  sudo: yes
  action: yum name={{ item }} state=present
  with_items:
    - ipa-server
    - ipa-server-trust-ad
    - freeradius
    - freeradius-utils
    - freeradius-ldap
    - freeradius-krb5
    - bind
    - bind-dyndb-ldap
  when: ansible_distribution != 'Fedora'

## Install the packages
- name: Install ipa and radiusd
  sudo: yes
  action: yum name={{ item }} state=present
  with_items:
    - freeipa-server
    - freeipa-server-trust-ad
    - freeradius
    - freeradius-utils
    - freeradius-ldap
    - freeradius-krb5
    - bind
    - bind-dyndb-ldap
  when: ansible_distribution == 'Fedora'

- name: Configure DNS firewall for all masters.
  sudo: yes
  firewalld: zone=internal permanent=true state=enabled service=dns immediate=true

- name: Configure IPA firewalld
  sudo: yes
  firewalld: zone=internal permanent=true state=enabled service={{ item }} immediate=true
  with_items:
    - kerberos
    - kpasswd
    - ldap
    - ldaps
    - radius
    - ntp
    - http
    - https
  when: "'linode_servers' not in group_names"

- name: Configure limited IPA firewalld
  sudo: yes
  #firewalld: zone=internal permanent=true state=enabled service={{ item }} immediate=true
  firewalld: zone=internal permanent=yes state=enabled immediate=yes rich_rule='rule family="ipv6" source address="{{ item[1] }}" service name="{{ item[0] }}" accept'
  with_nested:
    - [ 'kerberos', 'kpasswd', 'ldap', 'ldaps', 'radius', 'ntp', 'http', 'https' ]
    - [ '2001:44b8:2155:2c00::/56', '2a01:7e00::f03c:91ff:fe84:9e3e', '2400:8901::f03c:91ff:fe98:4593', '2a01:7e00::f03c:91ff:feae:5d82' ]
  when: "'linode_servers' in group_names"

- name: Configure limited IPA firewalld
  sudo: yes
  #firewalld: zone=internal permanent=true state=enabled service={{ item }} immediate=true
  firewalld: zone=internal permanent=yes state=enabled immediate=yes rich_rule='rule family="ipv4" source address="{{ item[1] }}" service name="{{ item[0] }}" accept'
  with_nested:
    - [ 'kerberos', 'kpasswd', 'ldap', 'ldaps', 'radius', 'ntp', 'http', 'https' ]
    - [ '176.58.111.213' ]
  when: "'linode_servers' in group_names"

- meta: flush_handlers

# Check that we have been promoted to a domain controller. /var/lib/ipa/sysrestore/sysrestore.state

- name: Test domain join
  sudo: yes
  action: stat path="/var/lib/ipa-client/sysrestore/sysrestore.state"
  register: state

- name: Fail if not domain controller
  sudo: yes
  action: fail msg="You should join this machine to the Domain with ipa-replica tools"
  when: state.stat.exists == false

# Should I have my custom named config in here?

- name: Ensure ipa services
  sudo: yes
  action: service name=ipa enabled=yes

- name: Configure radiusd
  sudo: yes
  action: copy src=raddb/{{ item }} dest=/etc/raddb/{{ item }} owner=root group=radiusd mode=0640
  with_items:
    - radiusd.conf
    - clients.conf
    - mods-available/ldap
    - mods-available/eap
    - sites-available/default
    - sites-available/inner-tunnel

- name: Configure ldap auth
  sudo: yes
  action: template src=ldap-bind dest=/etc/raddb/mods-enabled/ldap-bind owner=root group=radiusd mode=0640

- name: Symlink mods available
  sudo: yes
  action: file src=/etc/raddb/mods-available/{{ item }} dest=/etc/raddb/mods-enabled/{{ item }} state=link
  with_items:
    - ldap
    - eap

- name: Symlink sites available
  sudo: yes
  action: file src=/etc/raddb/sites-available/{{ item }} dest=/etc/raddb/sites-enabled/{{ item }} state=link
  with_items:
    - default
    - inner-tunnel


# Add radiusd keys

- name: Correct radius tls directory
  sudo: yes
  action: file path=/etc/pki/radius/ state=directory owner=radiusd group=radiusd mode=0750

- name: Check radiusd keys
  sudo: yes
  register: crtst
  action: stat path="/etc/pki/radius/server.pem.key"

# Clean up if they don't exist

- name: Deploy radiusd certificates
  sudo: yes
  action: command ipa-getcert request -k /etc/pki/radius/server.pem.key -f /etc/pki/radius/server.pem.crt -g 4096
  when: crtst.stat.exists == false

- name: Check dh
  sudo: yes
  register: dhst
  action: stat path=/etc/pki/radius/dh

- name: Create dhparams
  sudo: yes
  action: command openssl dhparam -outform PEM -out /etc/pki/radius/dh 2048
  when: dhst.stat.exists == false


- name: Fix radiusd cert permissions
  sudo: yes
  action: file path=/etc/pki/radius/{{ item }} owner=root group=radiusd mode=0640
  with_items:
    - server.pem.key
    - server.pem.crt
    - dh

- name: Start radiusd
  sudo: yes
  action: service name=radiusd state=started enabled=yes



# Ensure services?
