- name: Create backup home drive
  become: yes
  file: path=/home/backup state=directory owner=backup mode=0750

- name: Ensure excludes
  become: yes
  template: src=include-list dest=/home/backup/include-list owner=backup mode=0640

- name: Deploy rdiff-scripts
  become: yes
  template: src={{ item }} dest=/home/backup/{{ item }} owner=backup mode=0750
  with_items:
    - backup.sh
    - status.sh
    - clean.sh

- name: Push systemd unit files
  become: yes
  template: src=systemd/{{ item }} dest=/etc/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - backup.service
    - backup.timer
  notify: daemon-reload

- meta: flush_handlers

- name: Ensure services enabled
  become: yes
  ignore_errors: yes
  service: name=backup.timer enabled=no


