---
ds_instances:
    - name: test
      port: '389'
      secureport: '636'
      suffix: "dc=example,dc=com"
      passwd: testpassword
      # There is supposedly a module that hashs or can call an external command ... 
      hashedpasswd: "{SSHA512}ThPx/Zw/9SyJgYqZhLcarJnVKFtWRQJ5uqQYz/NOhvTrBccqHjYBjzzptY+CZwAnD4iSiV1CM6CM/cP76MFGdR5DBJcstjV8"
      nss_password: password

