
# Because this is a laptop we don't assume we have the static repos
#  like we do for our servers

# So run this *AFTER* common-bh, so that we can be guaranteed of firewalld
## The main reason is to lock down the wifi port

# For this to work on fedora 25 or more:
# yum install -y python2-dnf

## WARNING:

# Macbook pro add this to grub line
#   rd.blacklist=radeon
# REMOVE RHGB

- name: deploy default laptop configurations
  become: true
  action: template src=laptop/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - default/tlp
    - modprobe.d/i915.conf
    - modprobe.d/sdhci.conf
    - modprobe.d/radeon.conf

- name: deploy VGA switch on startup
  become: true
  action: template src=laptop/systemd/vgaswitch-boot.service dest=/etc/systemd/system/vgaswitch-boot.service owner=root group=root mode=0644

- name: deploy VGA switch on resume
  become: true
  action: template src=laptop/systemd/vgaswitch.service dest=/etc/systemd/system/vgaswitch.service owner=root group=root mode=0644

- name: deploy RHEL repos
  become: true
  action: template src=laptop/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - yum.repos.d/abrt-rhel-7-dogfooding-rhel-7.dev.repo
    - yum.repos.d/bluejeans.repo
    - yum.repos.d/centos-extras.repo
    - yum.repos.d/epel.repo
    - yum.repos.d/epel-testing.repo
    - yum.repos.d/google-talkplugin.repo
    - yum.repos.d/nux-desktop.repo
    - yum.repos.d/rcm-tools-rhel-7-workstation.repo
  when: ansible_distribution != 'Fedora'

- name: install default laptop packages
  become: true
  package: name={{ item }} state=present
  with_items:
    - graphviz
    - pwgen
    - tlp
    - ansible
    - copr-cli
    - cowsay
    - dconf-editor
    - docker
    - evolution
    - git
    - gimp
    - gnome-tweak-tool
    - irssi
    - ldapvi
    - libvirt
    - nmap
    - powertop
    - rhythmbox
    - samba-client
    - virt-install
    - virt-manager
    - vlc
    - wireshark
    - wireshark-gnome
    - openconnect
    - NetworkManager-openconnect
    - python-pip

# Should I restart these ? 

- name: ensure default laptop services
  become: true
  action: service name={{ item }} state=started enabled=yes
  with_items:
    - tlp
    - docker
    - vgaswitch
    - vgaswitch-boot

# Add docker0 to trusted zone

- name: Change default zone
  become: true
  shell: /usr/bin/firewall-cmd --permanent --zone=trusted --add-interface=docker0

#- name: Install docker-py
#  pip: name=docker-py executable=/usr/bin/pip
#  become: true

#- name: Ensure base images
#  become: true
#  action: docker_image name=centos:7

