
# Because this is a laptop we don't assume we have the static repos
#  like we do for our servers

# So run this *AFTER* common-bh, so that we can be guaranteed of firewalld
## The main reason is to lock down the wifi port

- name: install default laptop packages
  sudo: yes
  action: yum name={{ item }} state=present
  with_items:
    - graphviz
    - pwgen
    - tlp
    - ansible
    - bjnplugin
    - copr-cli
    - cowsay
    - dconf-editor
    - docker
    - dia
    - evolution
    - git
    - gimp
    - irssi
    - ldapvi
    - libvirt
    - nmap
    - powertop
    - rhythmbox
    - samba-client
    - virt-install
    - virt-manager
    - vlc
    - wireshark
    - wireshark-gnome

- name: deploy default laptop configurations
  sudo: yes
  action: template src=laptop/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - default/tlp
    - modprobe.d/i915.conf
    - yum.repos.d/abrt-rhel-7-dogfooding-rhel-7.dev.repo
    - yum.repos.d/bluejeans.repo
    - yum.repos.d/centos-extras.repo
    - yum.repos.d/epel.repo
    - yum.repos.d/epel-testing.repo
    - yum.repos.d/google-talkplugin.repo
    - yum.repos.d/nux-desktop.repo
    - yum.repos.d/rcm-tools-rhel-7-workstation.repo
    - yum.repos.d/redhat.repo

    # - squid/squid.conf
    # - dnf/dnf.conf

# Should I restart these ? 

- name: ensure default laptop services
  sudo: yes
  action: service name={{ item }} state=started enabled=yes
  with_items:
    - tlp
    - docker

# Add docker0 to trusted zone

- name: Change default zone
  sudo: yes
  shell: /usr/bin/firewall-cmd --permanent --zone=trusted --add-interface=docker0

