
# Because this is a laptop we don't assume we have the static repos
#  like we do for our servers

# So run this *AFTER* common-bh, so that we can be guaranteed of firewalld
## The main reason is to lock down the wifi port

- name: install default laptop packages
  sudo: yes
  action: yum name={{ item }} state=present
  with_items:
    - tlp
    - vim-nerdtree
    - cowsay
    - dconf-editor
    - dia
    - erlang
    - evolution
    - gimp
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-base
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer-plugins-bad-free
    - gstreamer-plugins-base
    - gstreamer-plugins-good
    - ldapvi
    - libvirt
    - pidgin
    - pidgin-otr
    - samba-client
    - tftp
    - tftp-server
    - virt-install
    - virt-manager
    - vlc
    - wireshark
    - wireshark-gnome

- name: deploy default laptop configurations
  sudo: yes
  action: template src=laptop/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - default/tlp
    - dnf/dnf.conf
    - squid/squid.conf

# Should I restart these ? 

- name: ensure default laptop services
  sudo: yes
  action: service name={{ item }} state=started enabled=yes
  with_items:
    - tlp

# Add docker0 to trusted zone

- name: Change default zone
  sudo: yes
  shell: /usr/bin/firewall-cmd --permanent --zone=trusted --add-interface=docker0
  notify:
    - reload firewalld

