
## Install the packages
- name: Install ipa and radiusd
  sudo: yes
  action: yum name={{ item }} state=present
  with_items:
    - ipa-server
    - ipa-server-trust-ad
    - freeradius
    - freeradius-utils
    - freeradius-ldap
    - freeradius-krb5

- name: Configure IPA firewalld
  sudo: yes
  firewalld: zone=internal permanent=true state=enabled service={{ item }}
  with_items:
    - kerberos
    - kpasswd
    - ldap
    - ldaps
    - radius
    - ntp
    - dns
    - http
    - https
  notify:
    - reload firewalld

- meta: flush_handlers

# Check that we have been promoted to a domain controller. /var/lib/ipa/sysrestore/sysrestore.state

- name: Test domain join
  sudo: yes
  action: stat path="/var/lib/ipa-client/sysrestore/sysrestore.state"
  register: state

- name: Fail if not domain controller
  sudo: yes
  action: fail msg="You should join this machine to the Domain with ipa-replica tools"
  when: state.stat.exists == false

# Should I have my custom named config in here?

- name: Ensure ipa services
  sudo: yes
  action: service name=ipa enabled=yes

- name: Configure radiusd
  sudo: yes
  action: copy src=raddb/{{ item }} dest=/etc/raddb/{{ item }} owner=root group=radiusd mode=0640
  with_items:
    - radiusd.conf
    - clients.conf
    - mods-available/ldap
    - mods-available/eap
    - sites-available/default
    - sites-available/inner-tunnel

- name: Configure ldap auth
  sudo: yes
  action: template src=ldap-bind dest=/etc/raddb/mods-enabled/ldap-bind owner=root group=radiusd mode=0640

- name: Symlink mods available
  sudo: yes
  action: file src=/etc/raddb/mods-available/{{ item }} dest=/etc/raddb/mods-enabled/{{ item }} state=link
  with_items:
    - ldap
    - eap

- name: Symlink sites available
  sudo: yes
  action: file src=/etc/raddb/sites-available/{{ item }} dest=/etc/raddb/sites-enabled/{{ item }} state=link
  with_items:
    - default
    - inner-tunnel


# Add radiusd keys

- name: Correct radius tls directory
  sudo: yes
  action: file path=/etc/pki/radius/ state=directory owner=radiusd group=radiusd mode=0750

- name: Check radiusd keys
  sudo: yes
  register: crtst
  action: stat path="/etc/pki/radius/server.pem.key"

# Clean up if they don't exist

- name: Deploy radiusd certificates
  sudo: yes
  action: command ipa-getcert request -k /etc/pki/radius/server.pem.key -f /etc/pki/radius/server.pem.crt -g 4096
  when: crtst.stat.exists == false

- name: Check dh
  sudo: yes
  register: dhst
  action: stat path=/etc/pki/radius/dh

- name: Create dhparams
  sudo: yes
  action: command openssl dhparam -outform PEM -out /etc/pki/radius/dh 2048
  when: dhst.stat.exists == false


- name: Fix radiusd cert permissions
  sudo: yes
  action: file path=/etc/pki/radius/{{ item }} owner=root group=radiusd mode=0640
  with_items:
    - server.pem.key
    - server.pem.crt
    - dh

- name: Start radiusd
  sudo: yes
  action: service name=radiusd state=started enabled=yes



# Ensure services?
