
- name: Configure IPA firewalld
  sudo: yes
  firewalld: zone=internal permanent=true state=enabled service={{ item }}
  with_items:
    - kerberos
    - kpasswd
    - ldap
    - ldaps
    - radius
    - ntp
    - dns
    - http
    - https
  notify:
    - reload firewalld

