
- name: Make sure SELinux is permissive as this is out-of-fhs
  sudo: yes
  shell: setenforce 0

- name: Run the 389DS testing suite
  sudo: yes
  shell: chdir="{{ ds_path }}/dirsrvtests" executable=/bin/zsh PYTHONPATH={{ lib389_path }} PREFIX={{ prefix }} py.test suites/dynamic-plugins

# Add other tests?
