

- name: Install default software
  sudo: yes
  package: name={{ item }} state=present
  with_items:
    - openldap-clients
    - chrony
    - sssd
    - sssd-ldap
    - oddjob
    - oddjob-mkhomedir

- name: Configure secure LDAP configurations
  sudo: yes
  template: src=ldap/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0600
  with_items:
    - sssd/sssd.conf
    - sudoers.d/bh_admins-sudo
  notify:
    - restart sssd

- name: Configure LDAP configurations
  sudo: yes
  template: src=ldap/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - pki/tls/certs/bh_ldap.crt
    - sysconfig/network
    - openldap/ldap.conf
    - hostname
    - hosts
    - chrony.conf
    - nsswitch.conf
    - pam.d/password-auth-ac
    - pam.d/system-auth-ac

- name: Disable NTP
  sudo: yes
  service: name=ntpd enabled=no state=stopped
  ignore_errors: yes

- name: Ensure services running
  sudo: yes
  service: name={{ item }} enabled=yes state=started
  with_items:
    - chronyd
    - sssd
    - sshd
    - oddjobd

- name: deploy ssh configurations
  sudo: yes
  action: template src=security/{{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - ssh/sshd_config

